#line 2 "gabc/gabc-score-determination-l.c"

#line 4 "gabc/gabc-score-determination-l.c"

#define  YY_INT_ALIGNED long int

/* A lexical scanner generated by flex */

#define yy_create_buffer gabc_score_determination__create_buffer
#define yy_delete_buffer gabc_score_determination__delete_buffer
#define yy_flex_debug gabc_score_determination__flex_debug
#define yy_init_buffer gabc_score_determination__init_buffer
#define yy_flush_buffer gabc_score_determination__flush_buffer
#define yy_load_buffer_state gabc_score_determination__load_buffer_state
#define yy_switch_to_buffer gabc_score_determination__switch_to_buffer
#define yyin gabc_score_determination_in
#define yyleng gabc_score_determination_leng
#define yylex gabc_score_determination_lex
#define yylineno gabc_score_determination_lineno
#define yyout gabc_score_determination_out
#define yyrestart gabc_score_determination_restart
#define yytext gabc_score_determination_text
#define yywrap gabc_score_determination_wrap
#define yyalloc gabc_score_determination_alloc
#define yyrealloc gabc_score_determination_realloc
#define yyfree gabc_score_determination_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE gabc_score_determination_restart(gabc_score_determination_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t gabc_score_determination_leng;

extern FILE *gabc_score_determination_in, *gabc_score_determination_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up gabc_score_determination_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up gabc_score_determination_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via gabc_score_determination_restart()), so that the user can continue scanning by
	 * just pointing gabc_score_determination_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when gabc_score_determination_text is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t gabc_score_determination_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow gabc_score_determination_wrap()'s to do buffer switches
 * instead of setting up a fresh gabc_score_determination_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void gabc_score_determination_restart (FILE *input_file  );
void gabc_score_determination__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE gabc_score_determination__create_buffer (FILE *file,int size  );
void gabc_score_determination__delete_buffer (YY_BUFFER_STATE b  );
void gabc_score_determination__flush_buffer (YY_BUFFER_STATE b  );
void gabc_score_determination_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void gabc_score_determination_pop_buffer_state (void );

static void gabc_score_determination_ensure_buffer_stack (void );
static void gabc_score_determination__load_buffer_state (void );
static void gabc_score_determination__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER gabc_score_determination__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE gabc_score_determination__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE gabc_score_determination__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE gabc_score_determination__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *gabc_score_determination_alloc (yy_size_t  );
void *gabc_score_determination_realloc (void *,yy_size_t  );
void gabc_score_determination_free (void *  );

#define yy_new_buffer gabc_score_determination__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        gabc_score_determination_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            gabc_score_determination__create_buffer(gabc_score_determination_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        gabc_score_determination_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            gabc_score_determination__create_buffer(gabc_score_determination_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define gabc_score_determination_wrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *gabc_score_determination_in = (FILE *) 0, *gabc_score_determination_out = (FILE *) 0;

typedef int yy_state_type;

extern int gabc_score_determination_lineno;

int gabc_score_determination_lineno = 1;

extern char *gabc_score_determination_text;
#define yytext_ptr gabc_score_determination_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up gabc_score_determination_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	gabc_score_determination_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int32_t yy_accept[307] =
    {   0,
        0,    1,    7,    7,    0,    0,   65,   65,   46,   46,
       52,   52,   49,   49,    5,    5,   57,   57,   71,   27,
       70,   27,   27,   24,    6,   24,   24,   24,   24,   24,
       24,   24,   24,   24,    2,    2,    3,    3,    1,    7,
        7,   70,   28,   47,   64,   29,   53,   62,   63,   54,
       55,   65,   66,   68,   67,   46,   53,   52,   53,   49,
       48,    5,    4,   57,   53,   26,    0,   25,    0,   24,
        6,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,    2,    1,    7,    7,    0,    7,    7,
        0,    7,    8,    8,   28,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   65,   69,   46,
        0,   52,    0,   49,   48,    5,    4,   57,    0,   25,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,    7,    0,    0,    0,   40,   38,
        0,   30,    0,    0,    0,    0,    0,   50,   61,    0,
        0,    0,    0,    0,    0,    0,    0,   24,   24,    0,
       24,   24,   24,   15,   24,   11,   24,   24,   24,   24,
        0,    0,    0,   59,    0,   42,   44,   34,   36,   41,
       39,   33,    0,    0,    0,    0,   51,    0,   24,   24,
       24,    0,   24,   24,    0,    0,   24,   24,   24,   24,

       60,    0,   56,    0,   43,   45,   35,   37,    0,   24,
       19,    9,   24,   24,   24,   24,   24,   24,   24,   24,
        0,    0,    0,   31,   58,   24,   24,   24,   24,   24,
       24,   24,    0,   24,   24,   24,   32,   24,   24,    0,
       20,   24,   24,   24,   24,    0,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   18,   24,
       24,   24,   24,   22,    0,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   21,   24,   24,   24,   24,
       24,   24,   24,   24,   14,   24,   16,   24,   24,   24,
       13,   24,   24,   24,   24,   24,   24,   24,   12,   17,

       10,   24,   24,   24,   23,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    1,    6,    1,    7,    8,    1,    9,
       10,    1,    1,    1,   11,    1,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,   16,
        1,   17,    1,    1,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       19,    1,   20,    1,   18,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   18,   18,   30,   31,   32,
       33,   34,   18,   35,   36,   37,   38,   39,   18,   18,
       40,   18,   41,   42,   43,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   44,    1,    1,    1,
       45,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   46,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    1,    2,    3,    1,    1,    4,    5,    4,    5,
        6,    1,    7,    1,    8,    9,    1,    7,    4,    4,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
       10,    5,   10,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_base[329] =
    {   0,
        0,   44,   49,   51,   84,  121,   50,   55,   33,   40,
      688,  687,   58,   64,   66,   68,  686,  685,  700,  705,
      705,   75,  688,  687,  692,   48,   62,   64,   66,   73,
       85,   88,   94,   96,   98,  107,  705,  109,   76,  120,
      135,  139,    0,  705,  705,  705,  153,  684,  705,  705,
      705,    0,  705,  142,  705,    0,  136,    0,  683,    0,
      111,    0,  148,    0,  682,  152,  156,    0,    0,  682,
      705,  138,   97,  142,   95,  155,  147,  156,  166,  162,
      158,  161,  160,  192,  154,  198,  200,  202,  677,  204,
        0,  206,  208,  705,    0,  191,  661,  673,  672,  650,

      670,  656,  191,  648,  654,  666,  662,    0,  224,    0,
      208,    0,  642,    0,  229,    0,  231,    0,  659,    0,
      668,  209,  211,  667,  213,  227,  230,  236,  232,  237,
      238,  239,  241,  240,  662,  638,  645,  637,  705,  705,
      656,  705,  650,  654,  653,  652,  651,  705,  705,  650,
      649,  648,  231,  627,  633,  645,  631,  242,  245,  629,
      648,  248,  247,  647,  646,  645,  256,  257,  258,  260,
      638,  632,  636,  705,  631,  705,  705,  705,  705,  705,
      705,  705,  634,  633,  632,  631,  705,  610,  252,  259,
      261,  623,  271,  276,  260,  613,  277,  278,  616,  613,

      705,  587,  705,  590,  705,  705,  705,  705,  581,  282,
      586,  583,  284,  279,  287,  289,  288,  291,  561,  290,
      542,  533,  429,  705,  705,  293,  294,  434,  285,  297,
      300,  295,  410,  430,  292,  302,  705,  296,  304,  404,
      428,  319,  321,  322,  323,  405,  324,  325,  327,  326,
      328,  329,  330,  331,  423,  335,  332,  337,  422,  340,
      341,  342,  344,  421,  392,  349,  352,  353,  355,  360,
      363,  368,  364,  369,  357,  419,  372,  373,  374,  380,
      381,  384,  385,  365,  417,  388,  416,  390,  392,  393,
      207,  394,  397,  396,  398,  403,  400,  407,  175,  172,

      125,  408,  409,  415,  120,  705,  447,  457,  467,  477,
      487,  497,  507,  517,  522,  529,  539,  549,  559,  567,
      577,  585,  595,  605,  615,  625,   50,  635
    } ;

static yyconst flex_int32_t yy_def[329] =
    {   0,
      306,    1,  307,  307,  308,  308,  309,  309,  310,  310,
      311,  311,  312,  312,  313,  313,  314,  314,  306,  306,
      306,  306,  306,  315,  306,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  306,  306,  306,  306,  306,  316,
      317,  318,  319,  306,  306,  306,  306,  306,  306,  306,
      306,  320,  306,  306,  306,  321,   47,  322,  306,  323,
      306,  324,  306,  325,  306,  306,  306,  326,  327,  315,
      306,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  306,  306,  316,  317,  318,  317,  317,
      328,  318,  306,  306,  319,  306,  306,  306,  306,  306,

      306,  306,  306,  306,  306,  306,  306,  320,  306,  321,
      306,  322,  306,  323,  306,  324,  306,  325,  306,  326,
      327,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  328,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  315,  315,  327,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  315,  315,
      327,  327,  315,  315,  327,  327,  315,  315,  315,  315,

      306,  306,  306,  306,  306,  306,  306,  306,  306,  315,
      315,  327,  327,  315,  315,  327,  327,  327,  315,  315,
      327,  327,  306,  306,  306,  315,  327,  315,  315,  327,
      327,  327,  327,  315,  327,  327,  306,  315,  327,  327,
      315,  327,  327,  327,  327,  327,  327,  327,  315,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  315,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,

      327,  327,  327,  327,  327,    0,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306
    } ;

static yyconst flex_int32_t yy_nxt[752] =
    {   0,
       20,   20,   21,   20,   20,   20,   22,   20,   20,   20,
       23,   20,   24,   25,   20,   20,   20,   24,   20,   20,
       26,   24,   24,   27,   24,   24,   28,   24,   29,   30,
       31,   32,   33,   24,   24,   34,   24,   24,   24,   24,
       20,   20,   20,   20,   20,   20,   35,   36,   57,   37,
       38,   41,   41,   41,   41,   57,  121,   53,   69,   54,
       61,   61,   53,   42,   54,   42,   61,   61,   63,   63,
       63,   63,   69,   50,   69,   51,   69,   66,   66,   72,
       50,   67,   51,   69,   75,   73,   74,   39,   39,   39,
       44,   55,   45,   77,   46,   69,   55,   76,   69,   47,

       84,   84,   48,   49,   69,   69,   69,   69,   79,   84,
       84,   66,   66,  115,  115,   67,  125,   78,   82,   85,
       85,   85,   87,   87,   50,   80,   51,   44,   81,   45,
       69,   46,   83,  123,   88,   69,   47,   90,   90,   48,
       49,   93,   93,  109,  109,  109,  109,  111,   69,   91,
      117,  117,   69,   94,   66,   66,  306,   69,   66,   66,
      306,   50,   67,   51,   96,   69,   69,  124,   69,  122,
       69,   69,   69,   97,   98,   99,   69,  100,  127,  128,
      134,  101,   69,  126,  102,   69,  132,  129,  103,  104,
      105,  106,  131,  133,   84,   84,  130,   85,   85,   85,

       87,   87,   90,   90,  306,  306,   90,   90,   87,   87,
       93,   93,   88,  144,   91,  136,  306,   69,   91,   69,
       88,   69,  137,   69,  145,  109,  109,  109,  109,  150,
      151,  115,  115,  117,  117,  161,  152,   69,  159,  137,
       69,  158,   69,  153,  154,  155,   69,   69,   69,   69,
       69,   69,   69,  183,  165,   69,  163,   69,   69,  167,
      164,  166,   69,  162,  184,  170,   69,   69,   69,   69,
       69,   69,  210,  212,  168,  169,  193,  190,  189,  198,
      197,   69,  199,  216,  194,  200,   69,   69,   69,   69,
      217,  214,   69,  211,   69,   69,  215,   69,   69,   69,

       69,   69,   69,   69,   69,   69,   69,   69,  228,  241,
       69,  219,   69,  229,   69,  220,  227,  230,  226,  232,
      231,  238,  242,  243,  247,  234,  244,  239,  249,   69,
      248,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,  250,  252,   69,  254,   69,  255,  253,
       69,   69,   69,  262,   69,  263,  258,  257,  259,   69,
      260,  268,   69,   69,  261,   69,  264,   69,  269,  266,
       69,  267,  272,   69,   69,   69,  271,  274,   69,   69,
      270,  277,   69,   69,   69,  283,  275,  279,  276,  278,
       69,   69,  280,  282,   69,   69,  281,  285,   69,  284,

       69,  291,   69,   69,   69,  286,   69,   69,   69,  288,
       69,  290,  293,   69,  287,  289,  298,   69,   69,   69,
      295,  297,  296,  300,  292,   69,   69,   69,  294,   69,
      273,   69,   69,  265,  299,  301,  303,  256,   69,  251,
      246,  304,  245,  302,  240,  237,  305,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   60,   60,   60,

       60,   60,   60,   60,   60,   60,   60,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   70,   70,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   95,
       95,   95,  236,   95,  235,   95,   95,  108,  108,  108,
      108,  233,  108,  108,  108,  108,  108,  110,  110,  110,
      110,  110,  110,  110,  110,  112,  112,  112,  112,  112,
      112,  112,  112,   69,  112,  114,   69,  225,  114,  114,

      114,  114,  114,  114,  114,  116,  224,  223,  116,  116,
      116,  116,  116,  116,  116,  118,  118,  118,  118,  118,
      118,  118,  118,  222,  118,  120,  221,  120,  120,  120,
      120,  120,  120,  120,  120,  135,  135,  135,  135,  135,
      135,  135,  218,  135,  135,  213,  209,  208,  207,  206,
      205,  204,  203,  202,  201,   69,  196,  195,  192,  191,
      188,  187,  186,  185,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,   91,  160,   69,  157,
      156,  149,  148,  147,  146,  143,  142,  141,  140,  139,
      138,   91,   69,  119,  113,  107,   71,   69,   68,  306,

       65,   65,   59,   59,   19,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306
    } ;

static yyconst flex_int32_t yy_chk[752] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    9,    2,
        2,    3,    3,    4,    4,   10,  327,    7,   26,    7,
       13,   13,    8,    3,    8,    4,   14,   14,   15,   15,
       16,   16,   27,    9,   28,    9,   29,   22,   22,   26,
       10,   22,   10,   30,   28,   26,   27,    2,    2,    2,
        5,    7,    5,   30,    5,   31,    8,   29,   32,    5,

       35,   35,    5,    5,   33,   75,   34,   73,   32,   36,
       36,   38,   38,   61,   61,   38,   75,   31,   34,   39,
       39,   39,   40,   40,    5,   32,    5,    6,   33,    6,
      305,    6,   34,   73,   40,  301,    6,   41,   41,    6,
        6,   42,   42,   54,   54,   54,   54,   57,   72,   41,
       63,   63,   74,   42,   66,   66,   57,   77,   67,   67,
       57,    6,   67,    6,   47,   76,   78,   74,   81,   72,
       83,   82,   80,   47,   47,   47,   79,   47,   77,   78,
       83,   47,  300,   76,   47,  299,   81,   79,   47,   47,
       47,   47,   80,   82,   84,   84,   79,   85,   85,   85,

       86,   86,   87,   87,   88,   88,   90,   90,   92,   92,
       93,   93,   86,  103,   87,   96,   88,  291,   90,  122,
       92,  123,   96,  125,  103,  109,  109,  109,  109,  111,
      111,  115,  115,  117,  117,  125,  111,  126,  123,  111,
      127,  122,  129,  111,  111,  111,  128,  130,  131,  132,
      134,  133,  158,  153,  129,  159,  127,  163,  162,  131,
      128,  130,  189,  126,  153,  134,  167,  168,  169,  190,
      170,  191,  189,  191,  132,  133,  162,  159,  158,  168,
      167,  193,  169,  195,  163,  170,  194,  197,  198,  214,
      195,  193,  210,  190,  213,  229,  194,  215,  217,  216,

      220,  218,  235,  226,  227,  232,  238,  230,  214,  229,
      231,  197,  236,  215,  239,  198,  213,  216,  210,  218,
      217,  226,  230,  231,  235,  220,  232,  227,  238,  242,
      236,  243,  244,  245,  247,  248,  250,  249,  251,  252,
      253,  254,  257,  239,  242,  256,  244,  258,  245,  243,
      260,  261,  262,  252,  263,  253,  248,  247,  249,  266,
      250,  258,  267,  268,  251,  269,  254,  275,  260,  256,
      270,  257,  263,  271,  273,  284,  262,  266,  272,  274,
      261,  269,  277,  278,  279,  275,  267,  271,  268,  270,
      280,  281,  272,  274,  282,  283,  273,  278,  286,  277,

      288,  284,  289,  290,  292,  279,  294,  293,  295,  281,
      297,  283,  288,  296,  280,  282,  294,  298,  302,  303,
      290,  293,  292,  296,  286,  304,  287,  285,  289,  276,
      265,  264,  259,  255,  295,  297,  302,  246,  241,  240,
      234,  303,  233,  298,  228,  223,  304,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  312,  312,  312,

      312,  312,  312,  312,  312,  312,  312,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  315,  315,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  319,
      319,  319,  222,  319,  221,  319,  319,  320,  320,  320,
      320,  219,  320,  320,  320,  320,  320,  321,  321,  321,
      321,  321,  321,  321,  321,  322,  322,  322,  322,  322,
      322,  322,  322,  212,  322,  323,  211,  209,  323,  323,

      323,  323,  323,  323,  323,  324,  204,  202,  324,  324,
      324,  324,  324,  324,  324,  325,  325,  325,  325,  325,
      325,  325,  325,  200,  325,  326,  199,  326,  326,  326,
      326,  326,  326,  326,  326,  328,  328,  328,  328,  328,
      328,  328,  196,  328,  328,  192,  188,  186,  185,  184,
      183,  175,  173,  172,  171,  166,  165,  164,  161,  160,
      157,  156,  155,  154,  152,  151,  150,  147,  146,  145,
      144,  143,  141,  138,  137,  136,  135,  124,  121,  119,
      113,  107,  106,  105,  104,  102,  101,  100,   99,   98,
       97,   89,   70,   65,   59,   48,   25,   24,   23,   19,

       18,   17,   12,   11,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int gabc_score_determination__flex_debug;
int gabc_score_determination__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *gabc_score_determination_text;
#line 1 "gabc/gabc-score-determination.l"
#line 2 "gabc/gabc-score-determination.l"
/*
 * Gregorio is a program that translates gabc files to GregorioTeX
 * This file implements the score lexer.
 *
 * Gregorio score determination in gabc input.
 * Copyright (C) 2006-2015 The Gregorio Project (see CONTRIBUTORS.md)
 *
 * This file is part of Gregorio.
 * 
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 * 
 * You should have received a copy of the GNU General Public License along with 
 * this program.  If not, see <http://www.gnu.org/licenses/>. 
 */

#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "struct.h"
#include "messages.h"
#include "bool.h"
#include "support.h"

#include "gabc.h"
#include "gabc-score-determination.h"
#include "gabc-score-determination-y.h"

static unsigned char style_stack = 0;
static bool eof_found = false;

#define YY_NO_INPUT

#define YY_INPUT(buf,result,max_size) \
    if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) { \
        int c = '*'; \
        size_t n; \
        for (n = 0; n < max_size \
                && (c = getc(gabc_score_determination_in)) != EOF \
                && c != '\n'; ++n ) { \
            buf[n] = (char) c; \
        } \
        if (c == '\n') { \
            buf[n++] = (char) c; \
        } \
        if (c == EOF && ferror(gabc_score_determination_in)) { \
            YY_FATAL_ERROR("input in flex scanner failed"); \
        } \
        result = n; \
    } else { \
        errno=0; \
        while ((result = fread(buf, 1, max_size, gabc_score_determination_in)) \
                == 0 && ferror(gabc_score_determination_in)) { \
            if (errno != EINTR) { \
                YY_FATAL_ERROR("input in flex scanner failed"); \
                break; \
            } \
            errno = 0; \
            clearerr(gabc_score_determination_in); \
        } \
    } \
    gabc_digest(buf, result)

#define YY_USER_ACTION gabc_update_location(&gabc_score_determination_lloc, \
        gabc_score_determination_text, gabc_score_determination_leng);









/* The expression for attribute below is rather messy because we allow
for (a) single-line values, ending with a semicolon at end of line or a
double semicolon, (b) multi-line values, which end at a double
semicolon. */
#line 832 "gabc/gabc-score-determination-l.c"

#define INITIAL 0
#define attribute 1
#define score 2
#define notes 3
#define style 4
#define verb 5
#define comments 6
#define inicomments 7
#define alt 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int gabc_score_determination_lex_destroy (void );

int gabc_score_determination_get_debug (void );

void gabc_score_determination_set_debug (int debug_flag  );

YY_EXTRA_TYPE gabc_score_determination_get_extra (void );

void gabc_score_determination_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *gabc_score_determination_get_in (void );

void gabc_score_determination_set_in  (FILE * in_str  );

FILE *gabc_score_determination_get_out (void );

void gabc_score_determination_set_out  (FILE * out_str  );

yy_size_t gabc_score_determination_get_leng (void );

char *gabc_score_determination_get_text (void );

int gabc_score_determination_get_lineno (void );

void gabc_score_determination_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int gabc_score_determination_wrap (void );
#else
extern int gabc_score_determination_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( gabc_score_determination_text, gabc_score_determination_leng, 1, gabc_score_determination_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( gabc_score_determination_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( gabc_score_determination_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, gabc_score_determination_in))==0 && ferror(gabc_score_determination_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(gabc_score_determination_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int gabc_score_determination_lex (void);

#define YY_DECL int gabc_score_determination_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after gabc_score_determination_text and gabc_score_determination_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( gabc_score_determination_leng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(gabc_score_determination_text[gabc_score_determination_leng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! gabc_score_determination_in )
			gabc_score_determination_in = stdin;

		if ( ! gabc_score_determination_out )
			gabc_score_determination_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			gabc_score_determination_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				gabc_score_determination__create_buffer(gabc_score_determination_in,YY_BUF_SIZE );
		}

		gabc_score_determination__load_buffer_state( );
		}

	{
#line 108 "gabc/gabc-score-determination.l"

#line 1056 "gabc/gabc-score-determination-l.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of gabc_score_determination_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 307 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 705 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 109 "gabc/gabc-score-determination.l"
{
        /* BOM written by a lot of windows softwares when they write UTF-8 */
    }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 112 "gabc/gabc-score-determination.l"
{
        /* ignoring empty lines */
    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 115 "gabc/gabc-score-determination.l"
{
        BEGIN(inicomments);
    }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 118 "gabc/gabc-score-determination.l"
{
        BEGIN(INITIAL);
    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 121 "gabc/gabc-score-determination.l"
{
        /* ignored */
    }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 124 "gabc/gabc-score-determination.l"
{
        BEGIN(attribute);
        return COLON;
    }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 128 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return ATTRIBUTE;
    }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 133 "gabc/gabc-score-determination.l"
{
         BEGIN(INITIAL);
         return SEMICOLON;
    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 137 "gabc/gabc-score-determination.l"
{
         gabc_score_determination_lval.character = gabc_score_determination_text[5];
         return DEF_MACRO;
    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 141 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
         return NUMBER_OF_VOICES;
    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 146 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
         return NAME;
    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 151 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return SCORE_COPYRIGHT;
    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 156 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return GABC_COPYRIGHT;
    }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 161 "gabc/gabc-score-determination.l"
{
        /* DEPRECATED by 4.1 */
        return INITIAL_STYLE;
    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 165 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return MODE;
    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 170 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return MODE_MODIFIER;
    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 175 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return MODE_DIFFERENTIA;
    }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 180 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return ANNOTATION;
    }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 185 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return AUTHOR;
    }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 190 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return LANGUAGE;
    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 195 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return STAFF_LINES;
    }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 200 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return NABC_LINES;
    }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 205 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return ORISCUS_ORIENTATION;
    }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 210 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return OTHER_HEADER;
    }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 215 "gabc/gabc-score-determination.l"
{
       return VOICE_CHANGE;
    }
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 218 "gabc/gabc-score-determination.l"
{
       BEGIN(score);
       return END_OF_DEFINITIONS;
    }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 222 "gabc/gabc-score-determination.l"
{
        gregorio_messagef("det_score", VERBOSITY_ERROR, 0,
                _("unrecognized character: \"%c\" in definition part"),
                gabc_score_determination_text[0]);
    }
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 227 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return CHARACTERS;
    }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 232 "gabc/gabc-score-determination.l"
{
        return HYPHEN;
    }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 235 "gabc/gabc-score-determination.l"
{
        BEGIN(style);
        style_stack ++;
        return I_BEGINNING;
    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 240 "gabc/gabc-score-determination.l"
{
        return BNLBA;
    }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 243 "gabc/gabc-score-determination.l"
{
        return ENLBA;
    }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 246 "gabc/gabc-score-determination.l"
{
        style_stack --;
        if (style_stack == 0) {
            BEGIN(score);
        }
        return I_END;
    }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 253 "gabc/gabc-score-determination.l"
{
        BEGIN(style);
        style_stack ++;
        return TT_BEGINNING;
    }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 258 "gabc/gabc-score-determination.l"
{
        style_stack --;
        if (style_stack == 0) {
            BEGIN(score);
        }
        return TT_END;
    }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 265 "gabc/gabc-score-determination.l"
{
        BEGIN(style);
        style_stack ++;
        return UL_BEGINNING;
    }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 270 "gabc/gabc-score-determination.l"
{
        style_stack --;
        if (style_stack == 0) {
            BEGIN(score);
        }
        return UL_END;
    }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 277 "gabc/gabc-score-determination.l"
{
        BEGIN(style);
        style_stack ++;
        return C_BEGINNING;
    }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 282 "gabc/gabc-score-determination.l"
{
        style_stack --;
        if (style_stack == 0) {
            BEGIN(score);
        }
        return C_END;
    }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 289 "gabc/gabc-score-determination.l"
{
        BEGIN(style);
        style_stack ++;
        return B_BEGINNING;
    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 294 "gabc/gabc-score-determination.l"
{
        style_stack --;
        if (style_stack == 0) {
            BEGIN(score);
        }
        return B_END;
    }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 301 "gabc/gabc-score-determination.l"
{
        BEGIN(style);
        style_stack ++;
        return SC_BEGINNING;
    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 306 "gabc/gabc-score-determination.l"
{
        style_stack --;
        if (style_stack == 0) {
            BEGIN(score);
        }
        return SC_END;
    }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 313 "gabc/gabc-score-determination.l"
{
        BEGIN(style);
        style_stack ++;
        return SP_BEGINNING;
    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 318 "gabc/gabc-score-determination.l"
{
        style_stack --;
        if (style_stack == 0) {
            BEGIN(score);
        }
        return SP_END;
    }
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 325 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return CHARACTERS;
    }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 330 "gabc/gabc-score-determination.l"
{
        BEGIN(comments);
    }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 333 "gabc/gabc-score-determination.l"
{
        BEGIN(score);
    }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 336 "gabc/gabc-score-determination.l"
{
        /* ignored */
    }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 339 "gabc/gabc-score-determination.l"
{
        BEGIN(verb);
        return VERB_BEGINNING;
    }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 343 "gabc/gabc-score-determination.l"
{
        if (style_stack == 0) {
            BEGIN(score);
        } else {
            BEGIN(style);
        }
        return VERB_END;
    }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 351 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return CHARACTERS;
    }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 356 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return CHARACTERS;
    }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 361 "gabc/gabc-score-determination.l"
{
        return CENTER_BEGINNING;
    }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 364 "gabc/gabc-score-determination.l"
{
        return CENTER_END;
    }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 367 "gabc/gabc-score-determination.l"
{
        BEGIN(alt);
        return ALT_BEGIN;
    }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 371 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return CHARACTERS;
    }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 376 "gabc/gabc-score-determination.l"
{
        BEGIN(score);
        return ALT_END;
    }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 380 "gabc/gabc-score-determination.l"
{
        return EUOUAE_B;
    }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 383 "gabc/gabc-score-determination.l"
{
        return EUOUAE_E;
    }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 386 "gabc/gabc-score-determination.l"
{
        return TRANSLATION_CENTER_END;
    }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 389 "gabc/gabc-score-determination.l"
{
        return TRANSLATION_BEGINNING;
    }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 392 "gabc/gabc-score-determination.l"
{
        return TRANSLATION_END;
    }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 395 "gabc/gabc-score-determination.l"
{
        BEGIN(notes);
        return OPENING_BRACKET;
    }
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 399 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return NOTES;
    }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 404 "gabc/gabc-score-determination.l"
{
        return VOICE_CUT;
    }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 407 "gabc/gabc-score-determination.l"
{
        return NABC_CUT;
    }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 410 "gabc/gabc-score-determination.l"
{
        BEGIN(score);
        return CLOSING_BRACKET;
    }
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 414 "gabc/gabc-score-determination.l"
{
        BEGIN(score);
        return CLOSING_BRACKET_WITH_SPACE;
    }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(attribute):
case YY_STATE_EOF(score):
case YY_STATE_EOF(notes):
case YY_STATE_EOF(style):
case YY_STATE_EOF(verb):
case YY_STATE_EOF(comments):
case YY_STATE_EOF(inicomments):
case YY_STATE_EOF(alt):
#line 418 "gabc/gabc-score-determination.l"
{
        if (!eof_found) {
            eof_found = true;
            return END_OF_FILE;
        } else {
            yyterminate();
        }
    }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 426 "gabc/gabc-score-determination.l"
ECHO;
	YY_BREAK
#line 1735 "gabc/gabc-score-determination-l.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed gabc_score_determination_in at a new source and called
			 * gabc_score_determination_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = gabc_score_determination_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( gabc_score_determination_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * gabc_score_determination_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of gabc_score_determination_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					gabc_score_determination_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			gabc_score_determination_restart(gabc_score_determination_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) gabc_score_determination_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 307 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 307 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 306);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					gabc_score_determination_restart(gabc_score_determination_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( gabc_score_determination_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve gabc_score_determination_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void gabc_score_determination_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        gabc_score_determination_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            gabc_score_determination__create_buffer(gabc_score_determination_in,YY_BUF_SIZE );
	}

	gabc_score_determination__init_buffer(YY_CURRENT_BUFFER,input_file );
	gabc_score_determination__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void gabc_score_determination__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		gabc_score_determination_pop_buffer_state();
	 *		gabc_score_determination_push_buffer_state(new_buffer);
     */
	gabc_score_determination_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	gabc_score_determination__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (gabc_score_determination_wrap()) processing, but the only time this flag
	 * is looked at is after gabc_score_determination_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void gabc_score_determination__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	gabc_score_determination_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE gabc_score_determination__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) gabc_score_determination_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) gabc_score_determination_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination__create_buffer()" );

	b->yy_is_our_buffer = 1;

	gabc_score_determination__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with gabc_score_determination__create_buffer()
 * 
 */
    void gabc_score_determination__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		gabc_score_determination_free((void *) b->yy_ch_buf  );

	gabc_score_determination_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a gabc_score_determination_restart() or at EOF.
 */
    static void gabc_score_determination__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	gabc_score_determination__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then gabc_score_determination__init_buffer was _probably_
     * called from gabc_score_determination_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void gabc_score_determination__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		gabc_score_determination__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void gabc_score_determination_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	gabc_score_determination_ensure_buffer_stack();

	/* This block is copied from gabc_score_determination__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from gabc_score_determination__switch_to_buffer. */
	gabc_score_determination__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void gabc_score_determination_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	gabc_score_determination__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		gabc_score_determination__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void gabc_score_determination_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)gabc_score_determination_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)gabc_score_determination_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE gabc_score_determination__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) gabc_score_determination_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	gabc_score_determination__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to gabc_score_determination_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       gabc_score_determination__scan_bytes() instead.
 */
YY_BUFFER_STATE gabc_score_determination__scan_string (yyconst char * yystr )
{
    
	return gabc_score_determination__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to gabc_score_determination_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE gabc_score_determination__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) gabc_score_determination_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = gabc_score_determination__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in gabc_score_determination__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up gabc_score_determination_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		gabc_score_determination_text[gabc_score_determination_leng] = (yy_hold_char); \
		(yy_c_buf_p) = gabc_score_determination_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		gabc_score_determination_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int gabc_score_determination_get_lineno  (void)
{
        
    return gabc_score_determination_lineno;
}

/** Get the input stream.
 * 
 */
FILE *gabc_score_determination_get_in  (void)
{
        return gabc_score_determination_in;
}

/** Get the output stream.
 * 
 */
FILE *gabc_score_determination_get_out  (void)
{
        return gabc_score_determination_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t gabc_score_determination_get_leng  (void)
{
        return gabc_score_determination_leng;
}

/** Get the current token.
 * 
 */

char *gabc_score_determination_get_text  (void)
{
        return gabc_score_determination_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void gabc_score_determination_set_lineno (int  line_number )
{
    
    gabc_score_determination_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see gabc_score_determination__switch_to_buffer
 */
void gabc_score_determination_set_in (FILE *  in_str )
{
        gabc_score_determination_in = in_str ;
}

void gabc_score_determination_set_out (FILE *  out_str )
{
        gabc_score_determination_out = out_str ;
}

int gabc_score_determination_get_debug  (void)
{
        return gabc_score_determination__flex_debug;
}

void gabc_score_determination_set_debug (int  bdebug )
{
        gabc_score_determination__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from gabc_score_determination_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    gabc_score_determination_in = stdin;
    gabc_score_determination_out = stdout;
#else
    gabc_score_determination_in = (FILE *) 0;
    gabc_score_determination_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * gabc_score_determination_lex_init()
     */
    return 0;
}

/* gabc_score_determination_lex_destroy is for both reentrant and non-reentrant scanners. */
int gabc_score_determination_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		gabc_score_determination__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		gabc_score_determination_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	gabc_score_determination_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        gabc_score_determination_free((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * gabc_score_determination_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *gabc_score_determination_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *gabc_score_determination_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void gabc_score_determination_free (void * ptr )
{
	free( (char *) ptr );	/* see gabc_score_determination_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 426 "gabc/gabc-score-determination.l"




