#line 2 "gabc/gabc-score-determination-l.c"

#line 4 "gabc/gabc-score-determination-l.c"

#define  YY_INT_ALIGNED long int

/* A lexical scanner generated by flex */

#define yy_create_buffer gabc_score_determination__create_buffer
#define yy_delete_buffer gabc_score_determination__delete_buffer
#define yy_flex_debug gabc_score_determination__flex_debug
#define yy_init_buffer gabc_score_determination__init_buffer
#define yy_flush_buffer gabc_score_determination__flush_buffer
#define yy_load_buffer_state gabc_score_determination__load_buffer_state
#define yy_switch_to_buffer gabc_score_determination__switch_to_buffer
#define yyin gabc_score_determination_in
#define yyleng gabc_score_determination_leng
#define yylex gabc_score_determination_lex
#define yylineno gabc_score_determination_lineno
#define yyout gabc_score_determination_out
#define yyrestart gabc_score_determination_restart
#define yytext gabc_score_determination_text
#define yywrap gabc_score_determination_wrap
#define yyalloc gabc_score_determination_alloc
#define yyrealloc gabc_score_determination_realloc
#define yyfree gabc_score_determination_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE gabc_score_determination_restart(gabc_score_determination_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t gabc_score_determination_leng;

extern FILE *gabc_score_determination_in, *gabc_score_determination_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up gabc_score_determination_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up gabc_score_determination_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via gabc_score_determination_restart()), so that the user can continue scanning by
	 * just pointing gabc_score_determination_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when gabc_score_determination_text is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t gabc_score_determination_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow gabc_score_determination_wrap()'s to do buffer switches
 * instead of setting up a fresh gabc_score_determination_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void gabc_score_determination_restart (FILE *input_file  );
void gabc_score_determination__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE gabc_score_determination__create_buffer (FILE *file,int size  );
void gabc_score_determination__delete_buffer (YY_BUFFER_STATE b  );
void gabc_score_determination__flush_buffer (YY_BUFFER_STATE b  );
void gabc_score_determination_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void gabc_score_determination_pop_buffer_state (void );

static void gabc_score_determination_ensure_buffer_stack (void );
static void gabc_score_determination__load_buffer_state (void );
static void gabc_score_determination__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER gabc_score_determination__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE gabc_score_determination__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE gabc_score_determination__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE gabc_score_determination__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *gabc_score_determination_alloc (yy_size_t  );
void *gabc_score_determination_realloc (void *,yy_size_t  );
void gabc_score_determination_free (void *  );

#define yy_new_buffer gabc_score_determination__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        gabc_score_determination_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            gabc_score_determination__create_buffer(gabc_score_determination_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        gabc_score_determination_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            gabc_score_determination__create_buffer(gabc_score_determination_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define gabc_score_determination_wrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *gabc_score_determination_in = (FILE *) 0, *gabc_score_determination_out = (FILE *) 0;

typedef int yy_state_type;

extern int gabc_score_determination_lineno;

int gabc_score_determination_lineno = 1;

extern char *gabc_score_determination_text;
#define yytext_ptr gabc_score_determination_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up gabc_score_determination_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	gabc_score_determination_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 83
#define YY_END_OF_BUFFER 84
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int32_t yy_accept[430] =
    {   0,
        0,    1,    7,    7,    0,    0,   78,   78,   59,   59,
       65,   65,   62,   62,    5,    5,   70,   70,   84,   41,
       83,   41,   41,    6,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,    2,    2,
        3,    3,    1,    7,    7,   83,   42,   60,   77,   66,
       75,   76,   67,   68,   78,   79,   81,   80,   59,   66,
       65,   66,   62,   61,    5,    4,   70,   66,   40,    0,
       39,    6,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    2,    1,    7,

        7,    0,    7,    7,    0,    7,    8,    8,   42,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   78,   82,   59,    0,   65,    0,   62,   61,    5,
        4,   70,    0,   39,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        7,    0,    0,    0,   53,   51,    0,   43,    0,    0,
        0,    0,    0,   63,   74,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   28,    0,    0,   24,
        0,    0,    0,    0,    0,    0,    0,    0,   21,    0,

       11,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   72,    0,   55,   57,   47,   49,   54,   52,
       46,    0,    0,    0,    0,   64,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   16,
        0,    0,    0,    0,    0,   34,    0,    0,    0,   73,
        0,   69,    0,   56,   58,   48,   50,    0,    0,    0,
       23,    0,    0,    9,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       44,   71,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   45,    0,   18,    0,    0,    0,    0,    0,    0,
        0,   32,    0,    0,    0,   15,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   22,    0,
       17,    0,    0,    0,    0,    0,   25,   37,    0,    0,
        0,    0,    0,   38,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   14,    0,   29,    0,    0,    0,    0,
       19,   30,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   20,    0,    0,    0,    0,    0,    0,
        0,   13,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   12,    0,    0,   31,   36,    0,
        0,   10,    0,   35,    0,    0,    0,    0,    0,   33,
        0,    0,   26,    0,    0,    0,    0,   27,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    1,    6,    1,    7,    8,    1,    9,
       10,    1,    1,    1,   11,    1,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,   16,
        1,   17,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       18,    1,   19,    1,    1,    1,   20,   21,   22,   23,

       24,   25,   26,   27,   28,    1,   29,   30,   31,   32,
       33,   34,    1,   35,   36,   37,   38,   39,    1,   40,
       41,    1,   42,   43,   44,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   45,    1,    1,    1,
       46,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   47,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[48] =
    {   0,
        1,    1,    2,    3,    1,    1,    4,    5,    4,    5,
        1,    1,    1,    1,    6,    7,    1,    4,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    8,    5,    8,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_base[451] =
    {   0,
        0,   37,    1,    9,   70,   78,    7,   19,    3,   36,
      634,  633,    5,   31,   50,   52,  632,  631,  646,  651,
      651,   88,  634,  639,   66,  610,   48,   22,   82,  610,
      621,   83,   70,   39,   78,  605,  603,  610,  106,  115,
      651,  120,   83,  122,  128,  130,    0,  651,  651,  134,
      625,  651,  651,  651,    0,  651,  136,  651,    0,  124,
        0,  624,    0,  146,    0,  148,    0,  623,  156,  160,
        0,  651,  602,  598,  595,  598,  598,  598,  591,  602,
      605,  593,  600,  595,  590,  589,  583,  596,   90,  587,
      595,  591,  582,  573,  593,  588,  576,  165,  129,  174,

      176,  178,  595,  180,    0,  182,  184,  651,    0,   81,
      579,  591,  590,  568,  588,  574,  113,  566,  572,  584,
      581,    0,  196,    0,  181,    0,  560,    0,  201,    0,
      203,    0,  578,    0,  564,  576,  568,  565,  556,  561,
      567,  579,  567,  564,  561,  549,  559,  546,  559,  558,
      559,  556,  558,  558,  549,  541,  545,  542,  538,  546,
      556,  532,  539,  531,  651,  651,  550,  651,  545,  548,
      547,  546,  545,  651,  651,  544,  543,  542,  131,  521,
      527,  539,  525,  517,  521,  519,  651,  527,  526,  651,
      518,  537,  512,  513,  517,  506,  507,  507,  651,  530,

      651,  516,  503,  516,  513,  512,  499,  523,  495,  515,
      510,  513,  651,  509,  651,  651,  651,  651,  651,  651,
      651,  511,  510,  509,  508,  651,  487,  503,  496,  486,
      485,  487,  505,   27,  497,  481,  495,  494,  491,  651,
      482,  476,  482,  485,  497,  651,  485,  474,  475,  651,
      484,  651,  486,  651,  651,  651,  651,  485,  464,  476,
      651,  471,  461,  651,  464,  472,  458,  466,  463,  466,
      456,  462,  478,  455,  476,  464,  450,  451,  463,  465,
      651,  651,  453,  445,  447,  458,  443,  441,  451,  441,
      462,  448,  443,  438,  436,  436,  433,  433,  437,  427,

      452,  651,  429,  651,  435,  425,  418,  422,  434,  419,
      419,  651,  420,  429,  427,  651,  431,  416,  187,  425,
      414,  415,  435,  404,  409,  415,  431,  417,  403,  402,
      402,  426,  401,  394,  410,  396,  396,  398,  651,  394,
      651,  401,  395,  406,  386,  384,  413,  651,  384,  385,
      386,  385,  391,  651,  382,  395,  390,  383,  373,  402,
      382,  175,  378,  651,  382,  651,  376,  380,  380,  379,
      651,  651,  380,  380,  379,  365,  373,  374,  367,  361,
      373,  359,  362,  651,  369,  360,  370,  364,  379,  361,
      357,  651,  355,  362,  348,  347,  331,  333,  322,  324,

      310,  309,  308,  285,  651,  200,  184,  651,  651,  191,
      188,  651,  175,  651,  164,  170,  168,  168,  150,  651,
      133,  108,  651,   69,   73,   49,    1,  651,  651,  221,
      229,  237,  245,  253,  261,  269,  277,  285,  293,  301,
      309,  317,  323,  331,  337,  345,  353,  361,  369,  377
    } ;

static yyconst flex_int32_t yy_def[451] =
    {   0,
      430,  430,  431,  431,  432,  432,  433,  433,  434,  434,
      435,  435,  436,  436,  437,  437,  438,  438,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  439,  440,  441,  442,  429,  429,  429,
      429,  429,  429,  429,  443,  429,  429,  429,  444,   50,
      445,  429,  446,  429,  447,  429,  448,  429,  429,  429,
      449,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  439,

      440,  441,  440,  440,  450,  441,  429,  429,  442,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  443,  429,  444,  429,  445,  429,  446,  429,  447,
      429,  448,  429,  449,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      450,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,

      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,

      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,

      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,    0,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429
    } ;

static yyconst flex_int32_t yy_nxt[699] =
    {   0,
      429,  429,   21,   45,   45,  429,   22,   64,   64,  429,
       23,   45,   45,   24,   56,   46,   57,  429,   60,   25,
       26,   27,   28,   46,  428,   29,   56,   30,   57,   31,
       32,   33,   34,   64,   64,   35,   36,   37,   38,   39,
       40,   79,   41,   42,   53,   80,   54,   23,  265,   58,
       24,   60,   66,   66,   66,   66,   25,   26,   27,   28,
       91,   58,   29,   92,   30,  266,   31,   32,   33,   34,
      427,   77,   35,   36,   37,   38,   48,   53,   49,   54,
       78,   43,   43,   43,   48,   50,   49,   51,   52,   89,
       69,   69,  426,   50,   70,   51,   52,   73,  425,   93,

       74,   81,   86,   75,  162,   82,   87,   90,   98,   98,
      151,   53,  163,   54,   94,   88,   83,   98,   98,   53,
      152,   54,   69,   69,  101,  101,   70,   99,   99,   99,
      104,  104,  107,  107,  170,  125,  102,  123,  123,  123,
      123,  424,  105,  429,  108,  110,  171,  429,  129,  129,
      131,  131,  222,  111,  112,  113,  423,  114,   69,   69,
      422,  115,   69,   69,  223,  116,   70,   98,   98,  117,
      118,  119,  120,   99,   99,   99,  101,  101,  104,  104,
      429,  429,  104,  104,  101,  101,  107,  107,  102,  421,
      105,  420,  429,  419,  105,  418,  102,  123,  123,  123,

      123,  176,  177,  129,  129,  131,  131,  335,  178,  375,
      376,  417,  163,  416,  415,  414,  179,  180,  181,  413,
      336,   20,   20,   20,   20,   20,   20,   20,   20,   44,
       44,   44,   44,   44,   44,   44,   44,   47,   47,   47,
       47,   47,   47,   47,   47,   55,   55,   55,   55,   55,
       55,   55,   55,   59,   59,   59,   59,   59,   59,   59,
       59,   61,   61,   61,   61,   61,   61,   61,   61,   63,
       63,   63,   63,   63,   63,   63,   63,   65,   65,   65,
       65,   65,   65,   65,   65,   67,   67,   67,   67,   67,
       67,   67,   67,  100,  100,  100,  100,  100,  100,  100,

      100,  103,  103,  103,  103,  103,  103,  103,  103,  106,
      106,  106,  106,  106,  106,  106,  106,  109,  109,  109,
      412,  109,  109,  122,  122,  122,  122,  411,  122,  122,
      122,  124,  124,  124,  124,  124,  124,  126,  126,  126,
      126,  126,  126,  410,  126,  128,  409,  408,  128,  128,
      128,  128,  128,  130,  407,  406,  130,  130,  130,  130,
      130,  132,  132,  132,  132,  132,  132,  405,  132,  134,
      404,  134,  134,  134,  134,  134,  134,  161,  161,  161,
      161,  161,  403,  161,  161,  402,  401,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,

      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  374,  373,  372,  371,  370,  369,  368,  367,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,
      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  334,
      333,  332,  331,  330,  329,  328,  327,  326,  325,  324,
      323,  322,  321,  320,  319,  318,  317,  316,  315,  314,
      313,  312,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,

      283,  282,  281,  280,  279,  278,  277,  276,  275,  274,
      273,  272,  271,  270,  269,  268,  267,  264,  263,  262,
      261,  260,  259,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  249,  248,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  221,  220,
      219,  218,  217,  216,  215,  214,  213,  212,  211,  210,
      105,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  189,  188,  187,  186,  185,  184,  183,  182,  175,

      174,  173,  172,  169,  168,  167,  166,  165,  164,  105,
      160,  159,  158,  157,  156,  155,  154,  153,  150,  149,
      148,  147,  146,  145,  144,  143,  142,  141,  140,  139,
      138,  137,  136,  135,  133,  127,  121,   97,   96,   95,
       85,   84,   76,   72,   71,  429,   68,   68,   62,   62,
       19,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429

    } ;

static yyconst flex_int32_t yy_chk[699] =
    {   0,
        0,    0,    1,    3,    3,    0,    1,   13,   13,    0,
        1,    4,    4,    1,    7,    3,    7,    0,    9,    1,
        1,    1,    1,    4,  427,    1,    8,    1,    8,    1,
        1,    1,    1,   14,   14,    1,    1,    1,    1,    2,
        2,   28,    2,    2,    9,   28,    9,    2,  234,    7,
        2,   10,   15,   15,   16,   16,    2,    2,    2,    2,
       34,    8,    2,   34,    2,  234,    2,    2,    2,    2,
      426,   27,    2,    2,    2,    2,    5,   10,    5,   10,
       27,    2,    2,    2,    6,    5,    6,    5,    5,   33,
       22,   22,  425,    6,   22,    6,    6,   25,  424,   35,

       25,   29,   32,   25,  110,   29,   32,   33,   39,   39,
       89,    5,  110,    5,   35,   32,   29,   40,   40,    6,
       89,    6,   42,   42,   44,   44,   42,   43,   43,   43,
       45,   45,   46,   46,  117,   60,   44,   57,   57,   57,
       57,  422,   45,   60,   46,   50,  117,   60,   64,   64,
       66,   66,  179,   50,   50,   50,  421,   50,   69,   69,
      419,   50,   70,   70,  179,   50,   70,   98,   98,   50,
       50,   50,   50,   99,   99,   99,  100,  100,  101,  101,
      102,  102,  104,  104,  106,  106,  107,  107,  100,  418,
      101,  417,  102,  416,  104,  415,  106,  123,  123,  123,

      123,  125,  125,  129,  129,  131,  131,  319,  125,  362,
      362,  413,  125,  411,  410,  407,  125,  125,  125,  406,
      319,  430,  430,  430,  430,  430,  430,  430,  430,  431,
      431,  431,  431,  431,  431,  431,  431,  432,  432,  432,
      432,  432,  432,  432,  432,  433,  433,  433,  433,  433,
      433,  433,  433,  434,  434,  434,  434,  434,  434,  434,
      434,  435,  435,  435,  435,  435,  435,  435,  435,  436,
      436,  436,  436,  436,  436,  436,  436,  437,  437,  437,
      437,  437,  437,  437,  437,  438,  438,  438,  438,  438,
      438,  438,  438,  439,  439,  439,  439,  439,  439,  439,

      439,  440,  440,  440,  440,  440,  440,  440,  440,  441,
      441,  441,  441,  441,  441,  441,  441,  442,  442,  442,
      404,  442,  442,  443,  443,  443,  443,  403,  443,  443,
      443,  444,  444,  444,  444,  444,  444,  445,  445,  445,
      445,  445,  445,  402,  445,  446,  401,  400,  446,  446,
      446,  446,  446,  447,  399,  398,  447,  447,  447,  447,
      447,  448,  448,  448,  448,  448,  448,  397,  448,  449,
      396,  449,  449,  449,  449,  449,  449,  450,  450,  450,
      450,  450,  395,  450,  450,  394,  393,  391,  390,  389,
      388,  387,  386,  385,  383,  382,  381,  380,  379,  378,

      377,  376,  375,  374,  373,  370,  369,  368,  367,  365,
      363,  361,  360,  359,  358,  357,  356,  355,  353,  352,
      351,  350,  349,  347,  346,  345,  344,  343,  342,  340,
      338,  337,  336,  335,  334,  333,  332,  331,  330,  329,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  318,
      317,  315,  314,  313,  311,  310,  309,  308,  307,  306,
      305,  303,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  280,  279,  278,  277,  276,  275,  274,  273,  272,
      271,  270,  269,  268,  267,  266,  265,  263,  262,  260,

      259,  258,  253,  251,  249,  248,  247,  245,  244,  243,
      242,  241,  239,  238,  237,  236,  235,  233,  232,  231,
      230,  229,  228,  227,  225,  224,  223,  222,  214,  212,
      211,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      200,  198,  197,  196,  195,  194,  193,  192,  191,  189,
      188,  186,  185,  184,  183,  182,  181,  180,  178,  177,
      176,  173,  172,  171,  170,  169,  167,  164,  163,  162,
      161,  160,  159,  158,  157,  156,  155,  154,  153,  152,
      151,  150,  149,  148,  147,  146,  145,  144,  143,  142,
      141,  140,  139,  138,  137,  136,  135,  133,  127,  121,

      120,  119,  118,  116,  115,  114,  113,  112,  111,  103,
       97,   96,   95,   94,   93,   92,   91,   90,   88,   87,
       86,   85,   84,   83,   82,   81,   80,   79,   78,   77,
       76,   75,   74,   73,   68,   62,   51,   38,   37,   36,
       31,   30,   26,   24,   23,   19,   18,   17,   12,   11,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int gabc_score_determination__flex_debug;
int gabc_score_determination__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *gabc_score_determination_text;
#line 1 "gabc/gabc-score-determination.l"
#line 2 "gabc/gabc-score-determination.l"
/*
 * Gregorio is a program that translates gabc files to GregorioTeX
 * This file implements the score lexer.
 *
 * Gregorio score determination in gabc input.
 * Copyright (C) 2006-2015 The Gregorio Project (see CONTRIBUTORS.md)
 *
 * This file is part of Gregorio.
 * 
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 * 
 * You should have received a copy of the GNU General Public License along with 
 * this program.  If not, see <http://www.gnu.org/licenses/>. 
 */

#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "struct.h"
#include "messages.h"
#include "support.h"

#include "gabc.h"
#include "gabc-score-determination.h"
#include "gabc-score-determination-y.h"

static unsigned char style_stack = 0;

#define YY_NO_INPUT

#define YY_INPUT(buf,result,max_size) \
    if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) { \
        int c = '*'; \
        size_t n; \
        for (n = 0; n < max_size \
                && (c = getc(gabc_score_determination_in)) != EOF \
                && c != '\n'; ++n ) { \
            buf[n] = (char) c; \
        } \
        if (c == '\n') { \
            buf[n++] = (char) c; \
        } \
        if (c == EOF && ferror(gabc_score_determination_in)) { \
            YY_FATAL_ERROR("input in flex scanner failed"); \
        } \
        result = n; \
    } else { \
        errno=0; \
        while ((result = fread(buf, 1, max_size, gabc_score_determination_in)) \
                == 0 && ferror(gabc_score_determination_in)) { \
            if (errno != EINTR) { \
                YY_FATAL_ERROR("input in flex scanner failed"); \
                break; \
            } \
            errno = 0; \
            clearerr(gabc_score_determination_in); \
        } \
    } \
    gabc_digest(buf, result)

#define YY_USER_ACTION gabc_update_location(&gabc_score_determination_lloc, \
        gabc_score_determination_text, gabc_score_determination_leng);









/* The expression for attribute below is rather messy because we allow
for (a) single-line values, ending with a semicolon at end of line or a
double semicolon, (b) multi-line values, which end at a double
semicolon. */
#line 857 "gabc/gabc-score-determination-l.c"

#define INITIAL 0
#define attribute 1
#define score 2
#define notes 3
#define style 4
#define verb 5
#define comments 6
#define inicomments 7
#define alt 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int gabc_score_determination_lex_destroy (void );

int gabc_score_determination_get_debug (void );

void gabc_score_determination_set_debug (int debug_flag  );

YY_EXTRA_TYPE gabc_score_determination_get_extra (void );

void gabc_score_determination_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *gabc_score_determination_get_in (void );

void gabc_score_determination_set_in  (FILE * in_str  );

FILE *gabc_score_determination_get_out (void );

void gabc_score_determination_set_out  (FILE * out_str  );

yy_size_t gabc_score_determination_get_leng (void );

char *gabc_score_determination_get_text (void );

int gabc_score_determination_get_lineno (void );

void gabc_score_determination_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int gabc_score_determination_wrap (void );
#else
extern int gabc_score_determination_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( gabc_score_determination_text, gabc_score_determination_leng, 1, gabc_score_determination_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( gabc_score_determination_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( gabc_score_determination_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, gabc_score_determination_in))==0 && ferror(gabc_score_determination_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(gabc_score_determination_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int gabc_score_determination_lex (void);

#define YY_DECL int gabc_score_determination_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after gabc_score_determination_text and gabc_score_determination_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( gabc_score_determination_leng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(gabc_score_determination_text[gabc_score_determination_leng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! gabc_score_determination_in )
			gabc_score_determination_in = stdin;

		if ( ! gabc_score_determination_out )
			gabc_score_determination_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			gabc_score_determination_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				gabc_score_determination__create_buffer(gabc_score_determination_in,YY_BUF_SIZE );
		}

		gabc_score_determination__load_buffer_state( );
		}

	{
#line 106 "gabc/gabc-score-determination.l"

#line 1081 "gabc/gabc-score-determination-l.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of gabc_score_determination_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 430 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 651 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 107 "gabc/gabc-score-determination.l"
{
        /* BOM written by a lot of windows softwares when they write UTF-8 */
    }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 110 "gabc/gabc-score-determination.l"
{
        /* ignoring empty lines */
    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 113 "gabc/gabc-score-determination.l"
{
        BEGIN(inicomments);
    }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 116 "gabc/gabc-score-determination.l"
{
        BEGIN(INITIAL);
    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 119 "gabc/gabc-score-determination.l"
{
        /* ignored */
    }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 122 "gabc/gabc-score-determination.l"
{
        BEGIN(attribute);
        return COLON;
    }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 126 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return ATTRIBUTE;
    }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 131 "gabc/gabc-score-determination.l"
{
         BEGIN(INITIAL);
         return SEMICOLON;
    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 135 "gabc/gabc-score-determination.l"
{
         gabc_score_determination_lval.character = gabc_score_determination_text[5];
         return DEF_MACRO;
    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 139 "gabc/gabc-score-determination.l"
{
         return NUMBER_OF_VOICES;
    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 142 "gabc/gabc-score-determination.l"
{
         return NAME;
    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 145 "gabc/gabc-score-determination.l"
{
        return SCORE_COPYRIGHT;
    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 148 "gabc/gabc-score-determination.l"
{
        return GABC_COPYRIGHT;
    }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 151 "gabc/gabc-score-determination.l"
{
        return OFFICE_PART;
    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 154 "gabc/gabc-score-determination.l"
{
        return OCCASION;
    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 157 "gabc/gabc-score-determination.l"
{
        return METER;
    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 160 "gabc/gabc-score-determination.l"
{
        return COMMENTARY;
    }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 163 "gabc/gabc-score-determination.l"
{
        return ARRANGER;
    }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 166 "gabc/gabc-score-determination.l"
{
        return GABC_VERSION;
    }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 169 "gabc/gabc-score-determination.l"
{
        return INITIAL_STYLE;
    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 172 "gabc/gabc-score-determination.l"
{
        return MODE;
    }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 175 "gabc/gabc-score-determination.l"
{
        return ANNOTATION;
    }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 178 "gabc/gabc-score-determination.l"
{
        return AUTHOR;
    }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 181 "gabc/gabc-score-determination.l"
{
        return DATE;
    }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 184 "gabc/gabc-score-determination.l"
{
        return MANUSCRIPT;
    }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 187 "gabc/gabc-score-determination.l"
{
        return MANUSCRIPT_REFERENCE;
    }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 190 "gabc/gabc-score-determination.l"
{
        return MANUSCRIPT_STORAGE_PLACE;
    }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 193 "gabc/gabc-score-determination.l"
{
        return BOOK;
    }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 196 "gabc/gabc-score-determination.l"
{
        return TRANSCRIBER;
    }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 199 "gabc/gabc-score-determination.l"
{
        return GENERATED_BY;
    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 202 "gabc/gabc-score-determination.l"
{
        return CENTERING_SCHEME;
    }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 205 "gabc/gabc-score-determination.l"
{
        return LANGUAGE;
    }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 208 "gabc/gabc-score-determination.l"
{
        return TRANSCRIPTION_DATE;
    }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 211 "gabc/gabc-score-determination.l"
{
        return STYLE;
    }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 214 "gabc/gabc-score-determination.l"
{
        return VIRGULA_POSITION;
    }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 217 "gabc/gabc-score-determination.l"
{
        return GREGORIOTEX_FONT;
    }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 220 "gabc/gabc-score-determination.l"
{
        return NABC_LINES;
    }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 223 "gabc/gabc-score-determination.l"
{
        return USER_NOTES;
    }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 226 "gabc/gabc-score-determination.l"
{
       return VOICE_CHANGE;
    }
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 229 "gabc/gabc-score-determination.l"
{
       BEGIN(score);
       return END_OF_DEFINITIONS;
    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 233 "gabc/gabc-score-determination.l"
{
        gregorio_messagef("det_score", VERBOSITY_ERROR, 0,
                _("unrecognized character: \"%c\" in definition part"),
                gabc_score_determination_text[0]);
    }
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 238 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return CHARACTERS;
    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 243 "gabc/gabc-score-determination.l"
{
        BEGIN(style);
        style_stack ++;
        return I_BEGINNING;
    }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 248 "gabc/gabc-score-determination.l"
{
        return BNLBA;
    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 251 "gabc/gabc-score-determination.l"
{
        return ENLBA;
    }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 254 "gabc/gabc-score-determination.l"
{
        style_stack --;
        if (style_stack == 0) {
            BEGIN(score);
        }
        return I_END;
    }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 261 "gabc/gabc-score-determination.l"
{
        BEGIN(style);
        style_stack ++;
        return TT_BEGINNING;
    }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 266 "gabc/gabc-score-determination.l"
{
        style_stack --;
        if (style_stack == 0) {
            BEGIN(score);
        }
        return TT_END;
    }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 273 "gabc/gabc-score-determination.l"
{
        BEGIN(style);
        style_stack ++;
        return UL_BEGINNING;
    }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 278 "gabc/gabc-score-determination.l"
{
        style_stack --;
        if (style_stack == 0) {
            BEGIN(score);
        }
        return UL_END;
    }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 285 "gabc/gabc-score-determination.l"
{
        BEGIN(style);
        style_stack ++;
        return C_BEGINNING;
    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 290 "gabc/gabc-score-determination.l"
{
        style_stack --;
        if (style_stack == 0) {
            BEGIN(score);
        }
        return C_END;
    }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 297 "gabc/gabc-score-determination.l"
{
        BEGIN(style);
        style_stack ++;
        return B_BEGINNING;
    }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 302 "gabc/gabc-score-determination.l"
{
        style_stack --;
        if (style_stack == 0) {
            BEGIN(score);
        }
        return B_END;
    }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 309 "gabc/gabc-score-determination.l"
{
        BEGIN(style);
        style_stack ++;
        return SC_BEGINNING;
    }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 314 "gabc/gabc-score-determination.l"
{
        style_stack --;
        if (style_stack == 0) {
            BEGIN(score);
        }
        return SC_END;
    }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 321 "gabc/gabc-score-determination.l"
{
        BEGIN(style);
        style_stack ++;
        return SP_BEGINNING;
    }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 326 "gabc/gabc-score-determination.l"
{
        style_stack --;
        if (style_stack == 0) {
            BEGIN(score);
        }
        return SP_END;
    }
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 333 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return CHARACTERS;
    }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 338 "gabc/gabc-score-determination.l"
{
        BEGIN(comments);
    }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 341 "gabc/gabc-score-determination.l"
{
        BEGIN(score);
    }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 344 "gabc/gabc-score-determination.l"
{
        /* ignored */
    }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 347 "gabc/gabc-score-determination.l"
{
        BEGIN(verb);
        return VERB_BEGINNING;
    }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 351 "gabc/gabc-score-determination.l"
{
        if (style_stack == 0) {
            BEGIN(score);
        } else {
            BEGIN(style);
        }
        return VERB_END;
    }
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 359 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return CHARACTERS;
    }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 364 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return CHARACTERS;
    }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 369 "gabc/gabc-score-determination.l"
{
        return CENTER_BEGINNING;
    }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 372 "gabc/gabc-score-determination.l"
{
        return CENTER_END;
    }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 375 "gabc/gabc-score-determination.l"
{
        BEGIN(alt);
        return ALT_BEGIN;
    }
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 379 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return CHARACTERS;
    }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 384 "gabc/gabc-score-determination.l"
{
        BEGIN(score);
        return ALT_END;
    }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 388 "gabc/gabc-score-determination.l"
{
        return EUOUAE_B;
    }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 391 "gabc/gabc-score-determination.l"
{
        return EUOUAE_E;
    }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 394 "gabc/gabc-score-determination.l"
{
        return TRANSLATION_CENTER_END;
    }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 397 "gabc/gabc-score-determination.l"
{
        return TRANSLATION_BEGINNING;
    }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 400 "gabc/gabc-score-determination.l"
{
        return TRANSLATION_END;
    }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 403 "gabc/gabc-score-determination.l"
{
        BEGIN(notes);
        return OPENING_BRACKET;
    }
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 407 "gabc/gabc-score-determination.l"
{
        gabc_score_determination_lval.text =
                gregorio_strdup(gabc_score_determination_text);
        return NOTES;
    }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 412 "gabc/gabc-score-determination.l"
{
        return VOICE_CUT;
    }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 415 "gabc/gabc-score-determination.l"
{
        return NABC_CUT;
    }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 418 "gabc/gabc-score-determination.l"
{
        BEGIN(score);
        return CLOSING_BRACKET;
    }
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 422 "gabc/gabc-score-determination.l"
{
        BEGIN(score);
        return CLOSING_BRACKET_WITH_SPACE;
    }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 426 "gabc/gabc-score-determination.l"
ECHO;
	YY_BREAK
#line 1803 "gabc/gabc-score-determination-l.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(attribute):
case YY_STATE_EOF(score):
case YY_STATE_EOF(notes):
case YY_STATE_EOF(style):
case YY_STATE_EOF(verb):
case YY_STATE_EOF(comments):
case YY_STATE_EOF(inicomments):
case YY_STATE_EOF(alt):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed gabc_score_determination_in at a new source and called
			 * gabc_score_determination_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = gabc_score_determination_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( gabc_score_determination_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * gabc_score_determination_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of gabc_score_determination_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					gabc_score_determination_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			gabc_score_determination_restart(gabc_score_determination_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) gabc_score_determination_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 430 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 430 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 429);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					gabc_score_determination_restart(gabc_score_determination_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( gabc_score_determination_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve gabc_score_determination_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void gabc_score_determination_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        gabc_score_determination_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            gabc_score_determination__create_buffer(gabc_score_determination_in,YY_BUF_SIZE );
	}

	gabc_score_determination__init_buffer(YY_CURRENT_BUFFER,input_file );
	gabc_score_determination__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void gabc_score_determination__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		gabc_score_determination_pop_buffer_state();
	 *		gabc_score_determination_push_buffer_state(new_buffer);
     */
	gabc_score_determination_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	gabc_score_determination__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (gabc_score_determination_wrap()) processing, but the only time this flag
	 * is looked at is after gabc_score_determination_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void gabc_score_determination__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	gabc_score_determination_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE gabc_score_determination__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) gabc_score_determination_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) gabc_score_determination_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination__create_buffer()" );

	b->yy_is_our_buffer = 1;

	gabc_score_determination__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with gabc_score_determination__create_buffer()
 * 
 */
    void gabc_score_determination__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		gabc_score_determination_free((void *) b->yy_ch_buf  );

	gabc_score_determination_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a gabc_score_determination_restart() or at EOF.
 */
    static void gabc_score_determination__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	gabc_score_determination__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then gabc_score_determination__init_buffer was _probably_
     * called from gabc_score_determination_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void gabc_score_determination__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		gabc_score_determination__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void gabc_score_determination_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	gabc_score_determination_ensure_buffer_stack();

	/* This block is copied from gabc_score_determination__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from gabc_score_determination__switch_to_buffer. */
	gabc_score_determination__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void gabc_score_determination_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	gabc_score_determination__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		gabc_score_determination__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void gabc_score_determination_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)gabc_score_determination_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)gabc_score_determination_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE gabc_score_determination__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) gabc_score_determination_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	gabc_score_determination__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to gabc_score_determination_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       gabc_score_determination__scan_bytes() instead.
 */
YY_BUFFER_STATE gabc_score_determination__scan_string (yyconst char * yystr )
{
    
	return gabc_score_determination__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to gabc_score_determination_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE gabc_score_determination__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) gabc_score_determination_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in gabc_score_determination__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = gabc_score_determination__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in gabc_score_determination__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up gabc_score_determination_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		gabc_score_determination_text[gabc_score_determination_leng] = (yy_hold_char); \
		(yy_c_buf_p) = gabc_score_determination_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		gabc_score_determination_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int gabc_score_determination_get_lineno  (void)
{
        
    return gabc_score_determination_lineno;
}

/** Get the input stream.
 * 
 */
FILE *gabc_score_determination_get_in  (void)
{
        return gabc_score_determination_in;
}

/** Get the output stream.
 * 
 */
FILE *gabc_score_determination_get_out  (void)
{
        return gabc_score_determination_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t gabc_score_determination_get_leng  (void)
{
        return gabc_score_determination_leng;
}

/** Get the current token.
 * 
 */

char *gabc_score_determination_get_text  (void)
{
        return gabc_score_determination_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void gabc_score_determination_set_lineno (int  line_number )
{
    
    gabc_score_determination_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see gabc_score_determination__switch_to_buffer
 */
void gabc_score_determination_set_in (FILE *  in_str )
{
        gabc_score_determination_in = in_str ;
}

void gabc_score_determination_set_out (FILE *  out_str )
{
        gabc_score_determination_out = out_str ;
}

int gabc_score_determination_get_debug  (void)
{
        return gabc_score_determination__flex_debug;
}

void gabc_score_determination_set_debug (int  bdebug )
{
        gabc_score_determination__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from gabc_score_determination_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    gabc_score_determination_in = stdin;
    gabc_score_determination_out = stdout;
#else
    gabc_score_determination_in = (FILE *) 0;
    gabc_score_determination_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * gabc_score_determination_lex_init()
     */
    return 0;
}

/* gabc_score_determination_lex_destroy is for both reentrant and non-reentrant scanners. */
int gabc_score_determination_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		gabc_score_determination__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		gabc_score_determination_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	gabc_score_determination_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        gabc_score_determination_free((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * gabc_score_determination_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *gabc_score_determination_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *gabc_score_determination_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void gabc_score_determination_free (void * ptr )
{
	free( (char *) ptr );	/* see gabc_score_determination_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 426 "gabc/gabc-score-determination.l"




