/* Header for module mtx, generated by p2c 1.21alpha-07.Dec.93 */
#ifndef MTX_H
#define MTX_H


/* Details of M-Tx -> PMX translation */

#ifndef GLOBALS_H
#include "globals.h"
#endif


#ifdef MTX_G
# define vextern
#else
# define vextern extern
#endif

extern Void scanMusic PP((int voice, short *left_over));
extern Void markDebeamed PP((int voice, Char *note));
extern Void checkOctave PP((int voice, Char *note));
extern Char *rests PP((Char *Result, int len, int meterdenom, int blind));
extern Void initMTX PV();


#undef vextern

#endif /*MTX_H*/

/* End. */
