.TH "ebb" "1" "May 2004" "teTeX" "teTeX" 
.PP 
.SH "NAME" 
ebb \- extract a bounding box from JPEG, PNG, and PDF files
.PP 
.SH "SYNOPSIS" 
.PP 
\fBebb\fP  [ \fI -v\fP | \fI-b\fP  ] \fI graphic_file\fP
.PP 
.SH "DESCRIPTION" 
.PP 
\fBebb\fP extracts the bounding box from JPEG, PNG, and PDF files
(with lower- or uppercase extensions) and writes it into a file with
the extension \fB.bb\fP, together with some header information. These
files can then be used by \fBdvipdfm\fP or other programs.
.PP
.SH "OPTIONS" 
.HP
\fB\-v\fR : be verbose
.HP
\fB\-b\fR : Write .bb file in binary mode (has no effect on Linux and
other systems conforming to POSIX).
.HP
.PP 
.SH "AUTHOR" 
.PP 
\fBebb\fP was written by Mark A. Wicks.
.PP 
This manual page was written by Frank Küster <frank@kuesterei\&.ch>,
for the Debian GNU/Linux system\&.  It may be used and modified by
others without contacting the author\&.  Any mistakes or omissions in
the manual page are my fault; inquiries about or corrections to this
manual page should be directed to me (and not to the primary
author)\&.
