avl.o: $(srcdir)/avl.c \
  $(srcdir)/avl.h
avlstuff.o: $(srcdir)/avlstuff.c \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h
epdf.o: $(srcdir)/epdf.c \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h
macnames.o: $(srcdir)/macnames.c
mapfile.o: $(srcdir)/mapfile.c \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h
pkin.o: $(srcdir)/pkin.c \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h
subfont.o: $(srcdir)/subfont.c \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h
tounicode.o: $(srcdir)/tounicode.c \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h
ttf2afm.o: $(srcdir)/ttf2afm.c \
  $(srcdir)/../../kpathsea/kpathsea.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  $(srcdir)/../../kpathsea/absolute.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/c-dir.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/c-namemx.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-pathmx.h \
  $(srcdir)/../../kpathsea/c-stat.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/cnf.h \
  $(srcdir)/../../kpathsea/concatn.h \
  $(srcdir)/../../kpathsea/db.h \
  $(srcdir)/../../kpathsea/str-list.h \
  $(srcdir)/../../kpathsea/default.h \
  $(srcdir)/../../kpathsea/expand.h \
  $(srcdir)/../../kpathsea/fn.h \
  $(srcdir)/../../kpathsea/fontmap.h \
  $(srcdir)/../../kpathsea/hash.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/line.h \
  $(srcdir)/../../kpathsea/magstep.h \
  ../../kpathsea/paths.h \
  $(srcdir)/../../kpathsea/pathsearch.h \
  $(srcdir)/../../kpathsea/str-llist.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/readable.h \
  $(srcdir)/../../kpathsea/recorder.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/tex-glyph.h \
  $(srcdir)/../../kpathsea/tex-hush.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../../kpathsea/tilde.h \
  $(srcdir)/../../kpathsea/truncate.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../../kpathsea/xopendir.h \
  $(srcdir)/../../kpathsea/xstat.h \
  $(srcdir)/../pdftexdir/ptexmac.h \
  $(srcdir)/../pdftexdir/writettf.h \
  $(srcdir)/macnames.c
utils.o: $(srcdir)/utils.c \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/c-stat.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../../libs/md5/md5.h \
  $(srcdir)/../../../libs/zlib/zlib.h \
  $(srcdir)/../../../libs/zlib/zconf.h \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/libpng/png.h \
  $(srcdir)/../../../libs/zlib/zlib.h \
  $(srcdir)/../../../libs/libpng/pngconf.h \
  $(srcdir)/../../../libs/xpdf/xpdf/config.h
vfpacket.o: $(srcdir)/vfpacket.c \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h
writeenc.o: $(srcdir)/writeenc.c \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h
writefont.o: $(srcdir)/writefont.c \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h
writeimg.o: $(srcdir)/writeimg.c \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h \
  $(srcdir)/image.h \
  $(srcdir)/../../../libs/libpng/png.h \
  $(srcdir)/../../../libs/zlib/zlib.h \
  $(srcdir)/../../../libs/zlib/zconf.h \
  $(srcdir)/../../../libs/libpng/pngconf.h
writejbig2.o: $(srcdir)/writejbig2.c \
  $(srcdir)/writejbig2.h \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h \
  $(srcdir)/image.h \
  $(srcdir)/../../../libs/libpng/png.h \
  $(srcdir)/../../../libs/zlib/zlib.h \
  $(srcdir)/../../../libs/zlib/zconf.h \
  $(srcdir)/../../../libs/libpng/pngconf.h
writejpg.o: $(srcdir)/writejpg.c \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h \
  $(srcdir)/image.h \
  $(srcdir)/../../../libs/libpng/png.h \
  $(srcdir)/../../../libs/zlib/zlib.h \
  $(srcdir)/../../../libs/zlib/zconf.h \
  $(srcdir)/../../../libs/libpng/pngconf.h
writepng.o: $(srcdir)/writepng.c \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h \
  $(srcdir)/image.h \
  $(srcdir)/../../../libs/libpng/png.h \
  $(srcdir)/../../../libs/zlib/zlib.h \
  $(srcdir)/../../../libs/zlib/zconf.h \
  $(srcdir)/../../../libs/libpng/pngconf.h
writet1.o: $(srcdir)/writet1.c \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h
writet3.o: $(srcdir)/writet3.c \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h \
  $(srcdir)/../../kpathsea/tex-glyph.h \
  $(srcdir)/../../kpathsea/magstep.h
writettf.o: $(srcdir)/writettf.c \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h \
  $(srcdir)/writettf.h \
  $(srcdir)/macnames.c
writezip.o: $(srcdir)/writezip.c \
  $(srcdir)/ptexlib.h ../pdftexd.h \
  $(srcdir)/../texmfmp.h \
  $(srcdir)/../cpascal.h \
  $(srcdir)/../config.h \
  $(srcdir)/../../kpathsea/config.h \
  ../../kpathsea/c-auto.h \
  $(srcdir)/../../kpathsea/c-std.h \
  $(srcdir)/../../kpathsea/c-unistd.h \
  $(srcdir)/../../kpathsea/systypes.h \
  $(srcdir)/../../kpathsea/c-memstr.h \
  $(srcdir)/../../kpathsea/c-errno.h \
  $(srcdir)/../../kpathsea/c-minmax.h \
  $(srcdir)/../../kpathsea/c-limits.h \
  $(srcdir)/../../kpathsea/c-proto.h \
  $(srcdir)/../../kpathsea/debug.h \
  $(srcdir)/../../kpathsea/types.h \
  $(srcdir)/../../kpathsea/lib.h \
  $(srcdir)/../../kpathsea/progname.h \
  ../../web2c/c-auto.h \
  $(srcdir)/../../kpathsea/c-vararg.h \
  $(srcdir)/../../kpathsea/c-fopen.h \
  $(srcdir)/../../kpathsea/getopt.h \
  $(srcdir)/../../kpathsea/proginit.h \
  $(srcdir)/../../kpathsea/tex-file.h \
  $(srcdir)/../../kpathsea/variable.h \
  $(srcdir)/../help.h \
  $(srcdir)/../../kpathsea/c-pathch.h \
  $(srcdir)/../../kpathsea/c-ctype.h \
  $(srcdir)/../../kpathsea/tex-make.h \
  $(srcdir)/../texmfmem.h ../pdftexcoerce.h \
  $(srcdir)/../pdftexdir/pdftex.h \
  $(srcdir)/../pdftexdir/ptexlib.h \
  $(srcdir)/ptexmac.h \
  $(srcdir)/avlstuff.h \
  $(srcdir)/avl.h \
  $(srcdir)/../../../libs/obsdcompat/openbsd-compat.h \
  $(srcdir)/../../../libs/obsdcompat/includes.h \
  ../../../libs/xpdf/../obsdcompat/config.h \
  $(srcdir)/../../../libs/obsdcompat/defines.h \
  $(srcdir)/../../../libs/zlib/zlib.h \
  $(srcdir)/../../../libs/zlib/zconf.h
