.TH TEXFONT "1" "May 2004" "teTeX " "texfont.pdf"
.SH NAME
texfont \- font installation tool for ConTeXt
.PP
.SH "SYNOPSIS" 
\fBtexfont\fP [ \fIOPTION\fP \&.\&.\&.  ]
.PP 
.SH DESCRIPTION
.PP
TeXFont is a perl script that helps to set up and install TeX fonts.
It was designed for use with ConTeXt, but may also be helpful for
users of other formats, like plain TeX or LaTeX. Its use is described
in detail in the files mtexfont.pdf and mfont.pdf.
.PP 
.SH "OPTIONS" 
.PP 
.HP
\fB\-\-fontroot\fR=\fIpath\fR : texmf font root (automatically determined)
.HP
\fB\-\-sourcepath\fR=\fIpath\fR : when installing, copy from this path (default: .)
.HP
\fB\-\-sourcepath\fR=\fIauto\fR : locate and use vendor/collection
.HP
\fB\-\-vendor\fR=\fIname\fR : vendor name (first level directory)
.HP
\fB\-\-collection\fR=\fIname\fR : font collection (second level
directory)
.HP
\fB\-\-encoding\fR=\fIname\fR : encoding vector (default: texnansi)
.HP
\fB\-\-slant\fR=\fIs\fR : slant glyphs in font by factor (0.0 - 1.5)
.HP
\fB\-\-extend\fR=\fIs\fR : extend glyphs in font by factor (0.0 - 1.5)
.HP
\fB\-\-caps\fR=\fIs\fR : capitalize lowercase chars by factor (0.5 - 1.0)
.HP
\fB\-\-noligs\fR : remove ligatures
.HP
\fB\-\-install\fR : copy files from source to font tree
.HP
\fB\-\-listing\fR : list files on auto sourcepath
.HP
\fB\-\-remove\fR : remove files on auto sourcepath
.HP
\fB\-\-makepath\fR : when needed, create the paths
.HP
\fB\-\-test\fR : use test paths for vendor/collection
.HP
\fB\-\-show\fR : run tex on texfont.tex
.HP
\fB\-\-batch\fR : process given batch file
.HP
\fB\-\-weight\fR : multiple master weight
.HP
\fB\-\-width\fR : multiple master width
.HP
\fB\-\-expert\fR : also handle expert fonts
.HP
\fB\-\-help\fR : show some more info
.HP
.SH "SEE ALSO" 
.PP 
\fBtexexec\fP(1), \fBfontinst\fP(1), \fBtexshow\fP(1),
\fBtexutil\fP(1)\&.
.PP 
The TeXFont manual, \fImtexfont\&.pdf\fP\&
.PP 
The ConTeXt Font manual, \fImfonts\&.pdf\fP\&
.PP
The TeXExec manual, \fImtexexec\&.pdf\fP\&.
.PP 
Donald E\&. Knuth\'s \fIThe TeXbook\fP\&.
.PP 
.SH "AUTHOR" 
.IP 
This manual page was written by Frank Küster <frank@kuesterei\&.ch>,
for the Debian GNU/Linux system\&.  It may be used and modified by
others without contacting the author\&.  Any mistakes or omissions in
the manual page are my fault; inquiries about or corrections to this
manual page should be directed to me (and not to the primary
author)\&.
.IP 
The PDF manual and \fBtexfont\fP itself can be obtained from
<http://www\&.pragma-ade\&.com>
