Panner.o: Panner.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../string-utils.h \
  ../my-vsnprintf.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h
Tip.o: Tip.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  Tip.h \
  ../xdvi-debug.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h
help-window.o: help-window.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../version.h \
  message-window.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../x_util.h \
  ../string-utils.h \
  ../my-vsnprintf.h \
  ../util.h \
  topic-window.h \
  help-window.h
mag.o: mag.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../c-openmx.h \
  $(kpathsea_srcdir)/c-limits.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../events.h \
  ../dvi-draw.h \
  ../dvi-init.h \
  statusline.h \
  ../hypertex.h \
  mag.h \
  xm_toolbar.h \
  xm_menu.h \
  menu.h \
  xaw_menu.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  pagesel.h
menu.o: menu.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../events.h \
  menu.h \
  xm_menu.h \
  xaw_menu.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h 
message-window.o:  \
 message-window.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../string-utils.h \
  ../my-vsnprintf.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../util.h \
  ../x_util.h \
  message-window.h
pagesel.o: pagesel.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  xm_toolbar.h \
  xm_menu.h \
  menu.h \
  ../events.h \
  xaw_menu.h \
  ../x_util.h \
  message-window.h \
  pagesel.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../string-utils.h \
  ../my-vsnprintf.h \
  ../util.h \
  ../dvi-init.h \
  statusline.h \
  print-dialog.h \
  ../print-internal.h \
  ../dvi-init.h \
  ../search-internal.h \
  search-dialog.h \
  ../dvisel.h \
  ../print-internal.h \
  ../pagehist.h
print-dialog.o: print-dialog.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../my-vsnprintf.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  print-dialog.h \
  ../print-internal.h \
  ../dvi-init.h \
  print-log.h \
  ../events.h \
  ../dvi-init.h \
  ../string-utils.h \
  ../my-vsnprintf.h \
  ../util.h \
  ../x_util.h \
  message-window.h \
  pagesel.h \
  ../my-snprintf.h \
  sfSelFile.h \
  ../dvisel.h \
  ../print-internal.h \
  xlwradio.h \
  statusline.h \
  search-dialog.h \
  ../search-internal.h \
  search-dialog.h \
  ../dvisel.h \
  ../special.h 
print-log.o: print-log.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../xdvi-debug.h \
  print-dialog.h \
  ../print-internal.h \
  ../dvi-init.h \
  print-log.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../string-utils.h \
  ../my-vsnprintf.h \
  ../util.h \
  ../x_util.h \
  xlwradio.h 
search-dialog.o: search-dialog.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../events.h \
  ../dvi-init.h \
  search-dialog.h \
  ../search-internal.h \
  search-dialog.h \
  ../dvisel.h \
  ../dvi-init.h \
  ../print-internal.h \
  xlwradio.h \
  statusline.h \
  ../string-utils.h \
  ../my-vsnprintf.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../string_list.h \
  ../util.h \
  message-window.h \
  ../x_util.h \
  xm_menu.h \
  menu.h \
  xaw_menu.h 
selection.o: selection.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../events.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../encodings.h \
  message-window.h \
  selection.h \
  statusline.h
sfDir.o: sfDir.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h sfDir.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-stat.h 
sfDraw.o: sfDraw.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-stat.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  sfDraw.h \
  sfDir.h \
  $(kpathsea_srcdir)/c-dir.h \
  sfPath.h
sfPath.o: sfPath.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-stat.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  sfDir.h \
  $(kpathsea_srcdir)/c-dir.h \
  sfDraw.h \
  sfPath.h \
  sfSelFile.h
sfSelFile.o: sfSelFile.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../dvi-init.h \
  message-window.h \
  $(kpathsea_srcdir)/c-stat.h \
  sfDir.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_srcdir)/c-dir.h \
  sfPath.h \
  sfDraw.h \
  sfSelFile.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  xlwradio.h \
  ../x_util.h \
  $(kpathsea_srcdir)/c-fopen.h 
statusline.o: statusline.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../version.h \
  statusline.h \
  xm_menu.h \
  menu.h \
  ../events.h \
  xaw_menu.h \
  ../x_util.h \
  ../pagehist.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../my-vsnprintf.h \
  ../util.h 
topic-window.o: topic-window.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../version.h \
  topic-window.h \
  ../string-utils.h \
  ../my-vsnprintf.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../util.h \
  ../x_util.h 
xaw_bitmaps.o: xaw_bitmaps.c \
  xaw_bitmaps.h
xaw_menu.o: xaw_menu.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../c-openmx.h \
  ../events.h \
  ../dvi-draw.h \
  ../dvi-init.h \
  statusline.h \
  pagesel.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../x_util.h \
  xaw_menu.h \
  menu.h \
  xm_menu.h \
  message-window.h \
  ../my-snprintf.h \
  ../filehist.h \
  xaw_bitmaps.h
xicon.o: xicon.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  xicon.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../xdvi-debug.h \
  ../xdvi.icon \
  ../pixmaps/xdvi32x32.xpm \
  ../pixmaps/xdvi16x16.xpm \
  ../pixmaps/xdvi48x48.xpm
xlwradio.o: xlwradio.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../xdvi-debug.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  xaw_bitmaps.h \
  xlwradioP.h \
  xlwradio.h 
xm_colorsel.o: xm_colorsel.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  Tip.h \
  ../x_util.h \
  xm_colorsel.h \
  xm_prefsP.h \
  xm_prefs.h \
  ../events.h \
  ../dvi-draw.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  topic-window.h \
  ../version.h \
  ../search-internal.h \
  search-dialog.h \
  ../dvisel.h \
  ../dvi-init.h \
  ../print-internal.h
xm_filesel.o: xm_filesel.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  sfSelFile.h \
  ../dvi.h \
  ../string-utils.h \
  ../my-vsnprintf.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../util.h \
  ../events.h \
  message-window.h \
  ../dvi-init.h \
  ../x_util.h 
xm_menu.o: xm_menu.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  xm_menu.h \
  menu.h \
  ../events.h \
  xaw_menu.h \
  xm_toolbar.h \
  ../my-snprintf.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../x_util.h \
  ../version.h \
  statusline.h \
  ../pagehist.h \
  ../dvi-init.h \
  ../filehist.h \
  ../c-openmx.h \
  message-window.h
xm_prefs.o: xm_prefs.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../x_util.h \
  xm_colorsel.h \
  topic-window.h \
  ../version.h \
  message-window.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../events.h \
  xm_prefsP.h \
  xm_prefs.h \
  xm_prefs_appearance.h \
  xm_prefs_fonts.h \
  xm_prefs_helpers.h \
  xm_prefs_page.h \
  xm_prefs_scroll.h \
  ../dvi-draw.h \
  ../search-internal.h \
  search-dialog.h \
  ../dvisel.h \
  ../dvi-init.h \
  ../print-internal.h \
  statusline.h \
  xm_toolbar.h \
  xm_menu.h \
  menu.h \
  xaw_menu.h \
  pagesel.h
xm_prefs_appearance.o:  \
 xm_prefs_appearance.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../x_util.h \
  ../my-snprintf.h \
  xm_colorsel.h \
  topic-window.h \
  ../version.h \
  message-window.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../events.h \
  xm_toolbar.h \
  xm_menu.h \
  menu.h \
  xaw_menu.h \
  statusline.h \
  pagesel.h \
  xm_prefsP.h \
  xm_prefs_appearance.h
xm_prefs_fonts.o:  \
 xm_prefs_fonts.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../x_util.h \
  xm_colorsel.h \
  topic-window.h \
  ../version.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../events.h \
  ../hypertex.h \
  ../my-snprintf.h \
  xm_prefsP.h \
  xm_prefs_fonts.h
xm_prefs_helpers.o:  \
 xm_prefs_helpers.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../x_util.h \
  xm_colorsel.h \
  topic-window.h \
  ../version.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../string-utils.h \
  ../my-vsnprintf.h \
  ../util.h \
  ../string_list.h \
  message-window.h \
  ../events.h \
  xm_menu.h \
  menu.h \
  xaw_menu.h \
  xm_prefsP.h \
  xm_prefs.h \
  xm_prefs_helpers.h
xm_prefs_page.o: xm_prefs_page.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../x_util.h \
  xm_colorsel.h \
  topic-window.h \
  ../version.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../events.h \
  statusline.h \
  xm_prefsP.h \
  xm_prefs_page.h \
  ../my-snprintf.h
xm_prefs_scroll.o:  \
 xm_prefs_scroll.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../x_util.h \
  xm_colorsel.h \
  topic-window.h \
  ../version.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../events.h \
  ../dvi-init.h \
  statusline.h \
  xm_prefsP.h \
  xm_prefs_scroll.h \
  ../my-snprintf.h
xm_toolbar.o: xm_toolbar.c \
  ../xdvi-config.h \
  $(kpathsea_dir)/c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  pagesel.h \
  help-window.h \
  message-window.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/expand.h \
  statusline.h \
  ../dvi-init.h \
  ../events.h \
  ../dvi-draw.h \
  xm_menu.h \
  menu.h \
  xaw_menu.h \
  xm_toolbar.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  ../events.h \
  ../x_util.h \
  Tip.h \
  ../c-openmx.h \
  ../pixmaps/toolbar.xpm
