#!/usr/bin/env perl
# $Id: generate-fmtutil 5188 2007-10-14 20:32:44Z karl $
# Copyright 2007 Norbert Preining.
# This file is licensed under the GNU General Public License version 2
# or any later version.
# 
# generate fmtutil.cnf file from the data in the tlpdb and -- if present
# -- with TEXMFLOCAL/web2c/fmtutil-local.cnf

BEGIN {
  $^W = 1;
  $master = `kpsewhich -var-value=SELFAUTOPARENT`;
  chomp($master);
  if (-r "$master/tlpkg/TeXLive") {
    unshift (@INC, "$master/tlpkg");
  } else {
    die("Cannot find TeX Live's Perl modules, exiting!\n");
  }
}

use strict;

use TeXLive::TLConfig;
use TeXLive::TLPOBJ;
use TeXLive::TLPDB;
use TeXLive::TLUtils qw/kpsewhich tllog/;
use Getopt::Long;
use Pod::Usage;
use File::Path;

my $opt_debug = 0;
my $help = 0;
my $dest = "";
my $localconf = "";
our $master;

GetOptions("debug!", "dest=s" => \$dest, 
           "local=s" => \$localconf, "help|?" => \$help) or pod2usage(1);

pod2usage(-exitstatus => 0, -verbose => 2) if $help;

if ($opt_debug) {
  $::LOGLEVELFILE = $::LOG_DDDEBUG;
  $::LOGLEVELTERMINAL = $::LOG_DDDEBUG;
}

exit (&main ());

sub main
{
  # get the db.
  my $tlpdb = TeXLive::TLPDB->new ("root" => "$master");
  if (!defined($tlpdb)) {
    die "Cannot find texlive.tlpdb below $master: $!\n";
  }
  $dest || ($dest = kpsewhich("TEXMFSYSVAR") . "/web2c/fmtutil.cnf");
  $localconf || ($localconf = kpsewhich("TEXMFLOCAL") . "/web2c/fmtutil-local.cnf");
	tllog($::LOG_NORMAL, "writing fmtutil.cnf data to $dest\n");
  TeXLive::TLUtils::create_fmtutil($tlpdb, $dest, $localconf);
}


__END__

=head1 NAME

generate-fmtutil - generate fmtutil.cnf from a TLPDB and local additions

=head1 SYNOPSIS

generate-fmtutil [OPTION]... 

=head1 OPTIONS

=over 8

=item C<-dest> I<output file>

specifies the output file

=item C<-local> I<local conf file>

specifies the local additions

=back

The standard options C<-help> and C<-debug> are accepted.
See the tlpfiles documentation for details.

=head1 DESCRIPTION

Missing

=head1 AUTHORS AND COPYRIGHT

This script and its documentation were written for the TeX Live
distribution (L<http://tug.org/texlive>) and both are licensed under the
GNU General Public License Version 2 or later.

=cut

### Local Variables:
### perl-indent-level: 2
### tab-width: 2
### indent-tabs-mode: nil
### End:
# vim:set tabstop=2 expandtab: #
