#!/usr/bin/env perl
# $Id: generate-updmap 5188 2007-10-14 20:32:44Z karl $
# Copyright 2007 Norbert Preining.
# This file is licensed under the GNU General Public License version 2
# or any later version.
# 
# generate updmap.cfg file from the data in the tlpdb and -- if present
# -- with TEXMFLOCAL/web2c/updmap-local.cfg

BEGIN {
  $^W = 1;
  $master = `kpsewhich -var-value=SELFAUTOPARENT`;
  chomp($master);
  if (-r "$master/tlpkg/TeXLive") {
    unshift (@INC, "$master/tlpkg");
  } else {
    die("Cannot find TeX Live's Perl modules, exiting!\n");
  }
}

use strict;

use TeXLive::TLConfig;
use TeXLive::TLPOBJ;
use TeXLive::TLPDB;
use TeXLive::TLUtils qw/kpsewhich tllog/;
use Getopt::Long;
use Pod::Usage;
use File::Path;

our $master;
my $opt_debug = 0;
my $help = 0;
my $dest = "";
my $localconf = "";

GetOptions("debug!", "dest=s" => \$dest, "local=s" => \$localconf,
           "help|?" => \$help) or pod2usage(1);

pod2usage(-exitstatus => 0, -verbose => 2) if $help;

if ($opt_debug) {
  $::LOGLEVELFILE = $::LOG_DDDEBUG;
  $::LOGLEVELTERMINAL = $::LOG_DDDEBUG;
}

exit (&main ());

sub main
{
  # get the db.
  my $tlpdb = TeXLive::TLPDB->new ("root" => "$master");
  $dest || ($dest = kpsewhich("TEXMFSYSVAR") . "/web2c/updmap.cfg");
  $localconf || ($localconf = kpsewhich("TEXMFLOCAL") . "/web2c/updmap-local.cfg");
	tllog($::LOG_NORMAL, "$0: writing new updmap.cfg to $dest\n");
  TeXLive::TLUtils::create_updmap ($tlpdb, $dest, $localconf);
}


__END__

=head1 NAME

generate-updmap - generate updmap.cfg from a TeX Live db and local additions

=head1 SYNOPSIS

generate-updmap [OPTION]... 

=head1 OPTIONS

=over 8

=item C<-dest> I<output_file>

specifies the output file; defaults to
C<$TEXMFSYSVAR/texmf/web2c/updmap.cfg>.

=item C<-local> I<local_conf_file>

specifies the local additions, if any; defaults to
C<$TEXMFLOCAL/web2c/updmap-local.cfg>.

=back

The standard options C<-help> and C<-debug> are accepted.
See the tlpfiles documentation for details.

=head1 DESCRIPTION

B<generate-updmap> creates an updated C<updmap.cfg> file with the C<Map>
and C<MixedMap> entries taken from the TL database, plus (optionally)
local additions.

No repository actions are performed in any case.

=head1 AUTHORS AND COPYRIGHT

This script and its documentation were written for the TeX Live
distribution (L<http://tug.org/texlive>) and both are licensed under the
GNU General Public License Version 2 or later.

=cut

### Local Variables:
### perl-indent-level: 2
### tab-width: 2
### indent-tabs-mode: nil
### End:
# vim:set tabstop=2 expandtab: #
