.TH EPSTOPDF 1 "18 March 2010"
.\" $Id$
.SH NAME
epstopdf, repstopdf \- convert an EPS file to PDF
.SH SYNOPSIS
\fBepstopdf\fP [\fIoptions\fP] [\fIepsfile\fP]
.SH DESCRIPTION
\fBepstopdf\fP transforms the Encapsulated PostScript file \fIepsfile\fP
(or standard input) so that it is guaranteed to start at the 0,0
coordinate, and it sets a page size exactly corresponding to the
BoundingBox.  This means that when Ghostscript renders it, the result
needs no cropping, and the PDF MediaBox is correct.  By default, the
result is piped to Ghostscript and a PDF version written.
.P
If the bounding box is not right, of course, there are problems.
.SH OPTIONS
.IP "\fB--outfile\fP=\fIfile\fP"
write result to \fIfile\fP.  If this option is not given, and
\fB--nogs\fP or \fB--filter\fP is specified, write to standard output;
otherwise, the default is to construct the output file name by replacing
any extension in the input file with \fI.pdf\fP.
.IP "\fB--\fP[\fBno\fP]\fBcompress\fP"
use compression (default: on).
.IP "\fB--\fP[\fBno\fP]\fBdebug\fP"
write debugging info (default: off).
.IP "\fB--\fP[\fBno\fP]\fBembed\fP"
embed fonts (default: on).
.IP "\fB--\fP[\fBno\fP]\fBexact\fP"
scan ExactBoundingBox (default: off).
.IP "\fB--\fP[\fBno\fP]\fBfilter\fP"
read standard input and (unless \fB--outfile\fP is given) write standard
output(default: off).
.IP "\fB--\fP[\fBno\fP]\fBgs\fP"
run Ghostscript (default: on).  With \fB--nogs\fP, output (to standard
output by default) the PostScript that would normally be converted; that
is, the input PostScript as modified by \fBepstopdf\fP.
.IP "\fB--\fP[\fBno\fP]\fBhires\fP"
scan HiresBoundingBox (default: off).
.IP "\fB--gscmd\fP=\fIval\fP"
pipe output to \fIval\fP (default: [\fBgswin32c\fP on Windows, else \fBgs\fP])
.IP "\fB--res\fP=\fIdpi\fP"
set image resolution (default: [use gs default])
.IP "\fB--autorotate\fP=\fIval\fP"
set AutoRotatePages (default: None); recognized \fIval\fP choices:
None, All, PageByPage.  For EPS files, PageByPage is equivalent to All.
.IP "\fB--restricted\fP=\fIval\fP"
turn on restricted mode (default: [on for repstopdf, else off]);
this forbids the use of \fB--gscmd\fP and imposes restrictions on the input and
output file names according to the values of openin_any and openout_any (see
the Web2c manual, http://tug.org/web2c).
.IP "\fB--help\fP
display help message and exit
.IP "\fB--version\fP
display version information and exit
.SH EXAMPLES
Examples which produce "test.pdf":
.nf
epstopdf test.eps
produce postscript | epstopdf --filter >test.pdf
produce postscript | epstopdf -f -d -o=test.pdf
.fi
Example: look for HiresBoundingBox and produce corrected PostScript:
.nf
epstopdf -d --nogs --hires test.ps >testcorr.ps 
.fi
.SH BUGS
The case of "%%BoundingBox: (atend)" when input is not seekable (e.g.,
from a pipe) is not supported.
.PP
Report bugs in the program or this man page to tex-k@tug.org.  When
reporting bugs, please include an input file and the command line
options specified, so the problem can be reproduced.
.SH SEE ALSO
\fBgs\fP(1),
\fBpdfcrop\fP(1).
.PP
The epstopdf LaTeX package, part of the oberdiek bundle, which automates
running this script on the fly under TeX: http://ctan.org/pkg/epstopdf-pkg.
.SH AUTHOR
The script was originally written by Sebastian Rahtz, for Elsevier
Science, with subsequent contributions from Thomas Esser, Gerben Wierda
and many others.  Currently maintained by Karl Berry.
.PP
Man page originally written by Jim Van Zandt.
.PP
epstopdf home page: http://tug.org/epstopdf.
.PP
You may freely use, modify and/or distribute this file.
