.if t .ds TX T\\h'-0.1667m'\\v'0.20v'E\\v'-0.20v'\\h'-0.125m'X
.if t .ds LX L\\h'-0.36m'\\v'-0.15v'\\s-2A\\s+2\\h'-0.15m'\\v'0.15v'T\\h'-0.1667m'\\v'0.20v'E\\v'-0.20v'\\h'-0.125m'X
.TH MAKEJVF L
.SH NAME
makejvf \- Make Japanese VF file from Japanese \*(TX TFM file
.SH SYNOPSIS
\fBmakejvf\fR [\fI<options>\fR] \fI<\*(TX TFM file>\fR \fI<TFM name of PS font>\fR
.SH DESCRIPTION
\fBmakejvf\fR is a tool to generate Japanese VF file from Japanese \*(TX TFM
(JFM) file for use with dvips.
.TP 5
When processing Japanese texts, p\*(TX refers to JFM (min10.tfm, jis.tfm \
etc.), which includes definitions of some different character widths and \
metric glue/kerns. For most punctuations and quotation marks, the \
character widths are truncated to less than 1 zw (zenkaku-width; the \
width of ordinary Kanji characters), and metric glue/kerns are inserted \
as a substitute.
.TP 5
On the other hand, in Japanese PS fonts, all punctuations and quotation \
marks have the same character widths as ordinary Kanji characters. \
For this reason, when dvips processes the resulting DVI, these characters \
have to be shifted to the left by the amount of glue/kerns inserted.
.TP 5
To achieve this, Virtual fonts (VF) and PS TFM files are required; \
VF should include the commands of shifting characters, and PS TFM should \
have the exact character widths of PS fonts. \
The program \fBmakejvf\fR can be used for this purpose.
.SH OPTIONS
.PP
.TP 10
\fB-C\fR
Condensed ("Cho-tai") mode.
.TP 10
\fB-K\fI <TFMfile>\fR
Name of the PS font TFM for Kana (more exactly, non-Kanji) characters.
.TP 10
\fB-b\fI <integer>\fR
Base line shift amount; the \fIinteger\fR represents a relative value,
using the character height as a base of 1000.
When a positive integer is specified, the characters are lowered.
When a negative integer is specified, the characters are raised.
.TP 10
\fB-m\fR
Replace single/double quotation marks (', '') with prime quotation marks
(so-called "minute") in vertical writing.
.TP 10
\fB-a\fI <AFMfile>\fR
Name of the AFM file. Used for Kana-tsume mode.
This option is unsupported.
.TP 10
\fB-k\fI <integer>\fR
Kana-tsume (narrower spaces between Kana characters) margin amount;
the \fIinteger\fR represents a relative value, using the character width
as a base of 1000. This option should be accompanied with \fB-a\fR option.
This option is unsupported.
.TP 10
\fB-u\fI <Charset>\fR
UCS mode. Available charsets are: gb (GB = Simplified Chinese),
cns (CNS = Traditional Chinese), ks (KS = Korean),
jis (JIS = Japanese), jisq (JIS quote only).
.TP 10
\fB-J\fI <TFMfile>\fR
JIS encoded PS font TFM name for quote, double quote (with UCS mode)
.TP 10
\fB-U\fI <TFMfile>\fR
UCS encoded PS font TFM name for quote, double quote (with UCS mode)
.TP 10
\fB-3\fR
Use set3 (with UCS mode)
.TP 10
\fB-H\fR
Use half-width Katakana (with UCS mode)
.TP 10
\fB-i\fR
Start font ID from No. 0.
.TP 10
\fB-e\fR
Enhanced mode; the horizontal shift amount is determined from the
glue/kern table of input JFM file.
.TP 10
By default, \fBmakejvf\fR uses the hard-coded value as the horizontal \
shift amount, which is (mostly) optimized for Japanese fonts. \
When enhanced mode (option \fB-e\fR) is enabled, the shift amount is \
determined from the input p\*(TX TFM (JFM) file, which is likely to \
output most suitable VF for the JFM.
.TP 10
For most standard Japanese JFM (like jis.tfm and its derivatives), \
the output VFs from both modes will have no significant difference. \
For simplified/traditional Chinese JFM (like upschrm-h.tfm and \
uptchcrm-h.tfm), the output VF from enhanced mode will be better. \
For min10.tfm and its derivatives, enhanced mode should \fInever\fR be \
enabled, since the characterization in min10.tfm is non-standard.
.SH EXAMPLE
.TP 5
If you want to use min10 as Ryumin-Light-H, run
     makejvf min10.tfm rml
.TP 5
This generates min10.vf and rml.tfm. Put these files in an appropriate \
directory under TEXMF tree, and add the following line to psfonts.map.
     rml Ryumin-Light-H
.SH SEE ALSO
More detailed description of \fBmakejvf\fR in Japanese is available at
     $TEXMFDIST/doc/fonts/ptex-fonts/README_makejvf
.SH AUTHOR
This manual page was written by Japanese \*(TX Development Community \
<https://texjp.org>. For more information, see GitHub repository \
<https://github.com/texjporg/ptex-fonts>.
Many thanks to Atsuhito KOHDA <kohda@debian.org>, \
for providing another manpage in Debian GNU/Linux system.
