#!/bin/sh
# Test @quote-args facility.

: ${srcdir=.}

unset TEXINFO_OUTPUT
TMP=quote-args.out

cat > quote-args.samp <<EOT
*FIXME: Many arguments, separated by commas, are processed here*
natopocotuototam

EOT

../makeinfo --plaintex $srcdir/quote-args.txi | diff - quote-args.samp
exit_code=$?

rm quote-args.samp
exit $exit_code
