.\" Copyright (c) 1996,1997 Roger Kehr
.\" See section COPYING for conditions for redistribution
.TH xindy 1L "February 1997" "Roger Kehr" ""
.de BP
.sp
.ti \-.2i
\(**
..

.SH NAME
xindy \- a fle\fBx\fPible \fBind\fPexing s\fBy\fPstem

.SH SYNOPSIS
.hy 0
.na
.TP
.B xindy
.RB "[\|" \-t "\|]"
.RB "[\|" \-l\ \fIlogfile\fP "\|]"
.RB "[\|" \-o\ \fIoutfile\fP "\|]"
.RB "[\|" \-f\ \fIfilterprog\fP "\|]"
.RB "[\|" \-L\ \fIn\fP "\|]"
.RB "[\|" \-v "\|]"
.I indexstyle rawindex

.SH DESCRIPTION
.B xindy
is a general purpose index processor.

.SH OPTIONS
.TP
.B "\-o \fIoutfile"
Writes the tagged index to the specified file. If omitted, the name of
the \fIrawindex\fP is used with its extension changed to \fB.ind\fP.

.TP
.B "\-l \fIlogfile"
Writes logging information into the specified file.

.TP
.B "\-f \fInfilterprog"
Run \fIfilterprog\fP on \fIrawindex\fP before reading. The program
must act as a filter reading from stdin and writing to stdout.

.TP
.B "\-L \fIn"
Sets the logging level to \fIn\fI with  \fIn\fI one of {1,2,3}

.TP
.B "\-t"
Activates the \fBmarkup-trace\fP function. Writes symbolic
markup-tags to the final index which can be used to trace the markup
process.

.TP
.B \-v
Display the version number.

.TP
.B \-help
Show a summary of the command-line options.

.SH "SEE ALSO"
tex2xindy(1L),
makeindex(1L),
makeindex4(1L)

For detailed information about the format of the \fIindexstyle\fP and
the \fIrawindex\fP refer to the documentation that comes with \fBxindy\fP.

.SH "AUTHOR"
Roger Kehr, Institut fuer Theoretische Informatik, TH-Darmstadt

.SH COPYING
Copyright (c) 1996,1997 Roger Kehr.
.PP
Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.
.PP
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.
.PP
Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
