Copyright (C) 2009 Peter Breitenlohner <tex-live@tug.org>
You may freely use, modify and/or distribute this file.

This directory is the central repository for auxiliary files, mostly shell
scripts, needed to build the TeX Live (TL) tree.  They are used by all
packages `owned' by the TL tree, i.e., maintained as part of TL.

The file mkinstalldirs serves as master copy for the files used by the
native build systems of some packages.

