\input texinfo
@setfilename texlive.info
@settitle TeX Live: The xxx

@set version 2014/dev
@set month-year August 2013

@macro TL
@TeX{} Live
@end macro

@copying
This file documents the @TL{} system, etc.

Copyright @copyright{} 2013 Xxx & Yyy.

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.

@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries a copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).
@end ignore

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation
approved by the @TeX{} Users Group.
@end copying

@c Define new indices for commands, filenames, and options.
@defcodeindex cm
@defcodeindex fl
@defcodeindex op

@c Put everything in one index (arbitrarily chosen to be the concept index).
@syncodeindex cm cp
@syncodeindex fl cp
@syncodeindex fn cp
@syncodeindex ky cp
@syncodeindex op cp
@syncodeindex pg cp
@syncodeindex tp cp
@syncodeindex vr cp

@dircategory TeX
@direntry
* @TL: (texlive).                        The @TL{} System.
@end direntry


@titlepage
@title TeXLive
@subtitle for version @value{version}
@subtitle @value{month-year}
@author Xxx
@author Yxx
@author @url{http://tug.org/tex-live}

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage


@contents


@ifnottex
@node Top
@top The @TL{} System

This manual documents how to build, install, and use @TL{}.  It corresponds
to version @value{version}, released in @value{month-year}.

@menu
* Introduction::                Overview.

* Build System::                The @TL{} Build System.

* Index::                       General index.
@end menu
@end ifnottex


@node Introduction
@chapter Introduction

@cindex introduction
@cindex fundamental purpose of @TL{}

This manual corresponds to version @value{version} of the @TL{} system,
released in @value{month-year}.


@include build.texi

@node Index
@unnumbered Index

@printindex cp

@bye
