\input texinfo
@setfilename texlive.info

@set version 2014
@set month-year April 2014

@set mytitle Building @TeX{} Live (@value{version})
@settitle @value{mytitle}

@macro TL
@TeX{} Live
@end macro

@copying
This file documents the @TL{} build system and more.

Copyright @copyright{} 2013, 2014 Karl Berry & Peter Breitenlohner.

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.

@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries a copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).
@end ignore

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation
approved by the @TeX{} Users Group.
@end copying

@c Put everything in one index (arbitrarily chosen to be the concept index).
@syncodeindex fn cp
@syncodeindex ky cp
@syncodeindex pg cp
@syncodeindex tp cp
@syncodeindex vr cp

@dircategory TeX
@direntry
* Building TeX Live: (texlive). TL configuration and development.
@end direntry

@titlepage
@title @value{mytitle}
@subtitle @value{version} release
@subtitle @value{month-year}
@author Karl Berry
@author Peter Breitenlohner
@author @url{http://tug.org/tex-live}

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@shortcontents
@contents

@ifnottex
@node Top
@top @value{mytitle}

For an overview of this manual, @pxref{Introduction}.

@menu
* Introduction::                Overview.
* Build system::                The @TL{} build system.
* Index::                       General index.
@end menu
@end ifnottex


@node Introduction
@chapter Introduction

@cindex introduction

This manual (dated @value{month-year}) corresponds to the @TL{}
@value{version} release.

This manual is aimed at system installers and programmers, and focuses
on how to configure, build, and develop the @TL{} (TL) sources.  The
sources can be acquired in a number of ways: see
@url{http://tug.org/texlive/svn}.

This manual does not duplicate the (primarily user-level) information
found in other TL documentation resources, such as:

@itemize
@item The @TL{} web pages: @url{http://tug.org/texlive}.

@item The @TL{} user manual: @url{http://tug.org/texlive/doc.html}, or
run @code{texdoc texlive}.

@item Other @TeX{}-related Texinfo manuals (@pxref{,,,web2c, Web2c},
@ref{,,,kpathsea, Kpathsea}, etc.):
@url{http://tug.org/texinfohtml/}, or check the @samp{TeX} category in
the GNU Info system.

@item Package documentation:
@url{http://tug.org/texlive/Contents/live/doc.html}, or the
@file{doc.html} file at the top level of the installed TL.

@end itemize

@ignore
As an exception, the full documentation for @code{install-tl} and
@code{tlmgr} is included here, just because it is convenient to do so.
The same text is available online (linked from
@url{http://tug.org/texlive/doc.html}, or by giving @samp{--help} to
the program (or look at the end of the source file).
@end ignore

@include tlbuild.texi

@node Index
@unnumbered Index

@printindex cp

@bye
