Public domain.  Originally created by Karl Berry, 2005.

kpathsea-based programs.

afm2pl 0.7.03 - ok 5dec06
  http://tex.aanhet.net/afm2pl/

devnag - from devnag package installed in texmf-dist.

dvipdfmx 20050831 - ok 5dec06
  http://project.ktug.or.kr/dvipdfmx/snapshot/current/
  -> http://www.ctan.org/tex-archive/dviware/dvipdfmx/

dvipng 1.9 - ok 5dec06
  http://www.ctan.org/tex-archive/dviware/dvipng/
