Copyright 2006 Karl Berry.
You may freely use, modify and/or distribute this file.

afm2pl 0.7.03 - ok 5dec06
  http://tex.aanhet.net/afm2pl/

devnag - from devnag package installed in texmf-dist.

dvipdfmx 20050831 - ok 5dec06
  http://project.ktug.or.kr/dvipdfmx/snapshot/current/
  -> http://www.ctan.org/tex-archive/dviware/dvipdfmx/

dvipng 1.9 - ok 5dec06
  http://www.ctan.org/tex-archive/dviware/dvipng/

xdvik 22.84.10 - ok 4dec06
  http://xdvi.sourceforge.net/
