.TH DVITOMP 1 "27 May 2009" "dvitomp 1.201"
.\" man page by Jim Van Zandt <jrv@vanzandt.mv.com>         -*- nroff -*-
.SH NAME
dvitomp \- convert a TeX DVI file to a MetaPost MPXFILE
.SH SYNOPSIS
.B dvitomp
.RI [ options ]
.IR dvifile [.dvi]
.RI [ mpxfile [.mpx]]
.PP
.B mpost 
.B --dvitomp
.IR dvifile [.dvi]
.RI [ mpxfile [.mpx]]
.SH DESCRIPTION
\fBdvitomp\fP translates the given \fIdvifile\fP to a MetaPost
MPXFILE.  The default \fImpxfile\fP is the basename of \fIdvifile\fP
extended with ".mpx".
.SH OPTIONS
.IP \fB-help\fP
write usage summary and exit.
.IP \fB-version\fP
output version information and exit.
.SH BUGS
Email bug reports to metapost@tug.org.
