.TH NEWER 1 "21 June 2005" "Web2C @VERSION@"
.\"=====================================================================
.SH NAME
newer \- compare file modification times
.SH SYNOPSIS
.B newer
.RI [ option ]
.I src1 
[ 
.I src2 ... srcN
] 
.I target
.\"=====================================================================
.SH DESCRIPTION
Exit successfully if files
.I src1 ... srcN
exist and at least one of them is not older than
.IR target .
Also exit successfully if
.I target
doesn't exist.
.\"=====================================================================
.SH OPTIONS
.B newer
accepts the following options:
.TP
.B --help
.rb
Print help message and exit.
.TP
.B --quiet, -q
.rb
Do not print any output, including error messages.
.TP
.B --version
.rb
Print version information and exit.
.TP
.B --verbose, -v
.rb
List missing source files.  This is the default.
