run_tests.o: run_tests.c \
  run_tests.h \
  ../xdvi-config.h ../c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../hypertex.h \
  ../dvi-init.h \
  ../special.h \
  ../events.h \
  ../string-utils.h \
  ../my-vsnprintf.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h 
test1.o: test1.c \
  run_tests.h \
  ../xdvi-config.h ../c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../hypertex.h \
  ../dvi-init.h \
  ../special.h \
  ../events.h \
  ../string-utils.h \
  ../my-vsnprintf.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h 
test_dl_list.o: test_dl_list.c \
  run_tests.h \
  ../xdvi-config.h ../c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../hypertex.h \
  ../dvi-init.h \
  ../special.h \
  ../events.h \
  ../string-utils.h \
  ../my-vsnprintf.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  ../dl_list.h
test_string_list.o:  \
 test_string_list.c \
  run_tests.h \
  ../xdvi-config.h ../c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../hypertex.h \
  ../dvi-init.h \
  ../special.h \
  ../events.h \
  ../string-utils.h \
  ../my-vsnprintf.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h \
  ../string_list.h
test_string_utils.o:  \
 test_string_utils.c \
  ../xdvi-config.h ../c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  $(kpathsea_srcdir)/c-vararg.h \
  run_tests.h \
  ../hypertex.h \
  ../dvi-init.h \
  ../special.h \
  ../events.h \
  ../string-utils.h \
  ../my-vsnprintf.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h 
test_util.o: test_util.c \
  run_tests.h \
  ../xdvi-config.h ../c-auto.h \
  ../xdvi.h \
  ../xdvi-config.h \
  ../xdvi-debug.h \
  ../xdvi.h \
  ../version.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/config.h \
  $(kpathsea_dir)/c-auto.h \
  $(kpathsea_srcdir)/c-std.h \
  $(kpathsea_srcdir)/c-unistd.h \
  $(kpathsea_srcdir)/systypes.h \
  $(kpathsea_srcdir)/c-memstr.h \
  $(kpathsea_srcdir)/c-errno.h \
  $(kpathsea_srcdir)/c-minmax.h \
  $(kpathsea_srcdir)/c-limits.h \
  $(kpathsea_srcdir)/c-proto.h \
  $(kpathsea_srcdir)/debug.h \
  $(kpathsea_srcdir)/types.h \
  $(kpathsea_srcdir)/lib.h \
  $(kpathsea_srcdir)/progname.h \
  $(kpathsea_srcdir)/c-pathmx.h \
  $(kpathsea_srcdir)/c-dir.h \
  $(kpathsea_srcdir)/c-vararg.h \
  $(kpathsea_srcdir)/c-fopen.h \
  ../hypertex.h \
  ../dvi-init.h \
  ../special.h \
  ../events.h \
  ../string-utils.h \
  ../my-vsnprintf.h \
  $(kpathsea_srcdir)/tex-file.h \
  $(kpathsea_srcdir)/c-vararg.h \
  ../events.h \
  ../util.h \
  $(kpathsea_srcdir)/c-stat.h \
  $(kpathsea_srcdir)/hash.h \
  $(kpathsea_srcdir)/tex-file.h 
