#!/bin/bash

case "$arch" in
  *-linux)
    prepcmd="apt-get update; apt-get install -y --no-install-recommends bash gcc g++ make perl libfontconfig-dev libx11-dev libxmu-dev libxaw7-dev build-essential"
    ;;
  *-linuxmusl)
    prepcmd="apk update; apk add --no-progress bash gcc g++ make perl fontconfig-dev libx11-dev libxmu-dev libxaw-dev"
    ;;
  *)
    echo "Unsupported arch=$arch found!" >&2
    exit 1
    ;;
esac

docker run -e TL_MAKE_FLAGS="${TL_MAKE_FLAGS}" \
           -v ${TRAVIS_BUILD_DIR}:/texlive -w /texlive \
	   -it --rm $dockerimg sh -c "$prepcmd ; ./Build -C"


