//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by windvi.rc
//
#define IDS_APPNAME                     1
#define IDS_DESCRIPTION                 2
#define IDD_VERFIRST                    100
#define IDI_APPICON                     101
#define IDM_STATUSBAR                   102
#define IDR_TOOLBAR1                    113
#define DLGCONFIG                       119
#define IDD_MAGNIFY_DIALOG              122
#define IDD_VERDESC                     201
#define IDD_VERVERSION                  202
#define IDD_VERCOPY                     203
#define IDD_VERLAST                     204
#define IDD_TEXT                        205
#define IDD_CANCEL                      206
#define IDD_FILE                        207
#define IDM_HELPTOPICS                  304
#define IDS_NO_HELP                     504
#define IDB_BMP                         700
#define IDS_SYSMENU                     900
#define IDS_FILEMENU                    1000
#define IDC_CHECKALIASING               1001
#define IDC_CHECKALLOWSHELL             1002
#define IDC_CHECKGSALPHA                1003
#define IDC_CHECKHUSHCHARS              1004
#define IDC_CHECKHUSHCHECKSUMS          1005
#define IDC_CHECKHUSHSPECIALS           1006
#define IDC_CHECKINMEMORY               1007
#define IDC_CHECKLISTFONTS              1008
#define IDC_CHECKMAKEPK                 1009
#define IDC_CHECKPOSTSCRIPT             1010
#define IDC_CHECKREVIDEO                1011
#define IDC_CHECKSCAN                   1012
#define IDC_CHECKSINGLE                 1013
#define IDC_CHECKXFORM                  1014
#define IDC_COMBOMFMODE                 1015
#define IDC_COMBOPAPER                  1016
#define IDC_COMBO_BACK_COLOR            1017
#define IDC_COMBO_FORE_COLOR            1018
#define IDC_EDITALTFONT                 1019
#define IDC_EDITBDPI                    1020
#define IDC_EDITDENSITY                 1021
#define IDC_EDITGAMMA                   1022
#define IDC_EDITMGS1                    1023
#define IDC_EDITMGS2                    1024
#define IDC_EDITMGS3                    1025
#define IDC_LOG_EDIT                    1026
#define IDC_PAGE_NUMBER                 1027
#define IDC_SPIN_PAGE_NUMBER            1028
#define IDC_PRINT_PROGRESS_PAGE         1029
#define IDC_PRINT_PROGRESS_BAND         1030
#define IDC_MAG_CURSOR_CHECK            1031
#define IDC_MAG_RULERS_CHECK            1032
#define IDC_CHECKLOG                    1033
#define IDM_ABOUT                       2001
#define IDM_EXIT                        2002
#define IDM_FILECLOSE                   2003
#define IDM_FILEOPEN                    2004
#define IDM_FILEPAGESU                  2005
#define IDM_FILEPRINT                   2006
#define IDM_FILEPRINTDVIPS              2007
#define IDM_FILEPRINTSU                 2008
#define IDM_FIRSTPAGE                   2009
#define IDM_GOTOPAGE                    2010
#define IDM_KEEPPOS                     2011
#define IDM_LASTPAGE                    2012
#define IDM_NEXT10                      2013
#define IDM_NEXT5                       2014
#define IDM_NEXTPAGE                    2015
#define IDM_PREVIOUS10                  2016
#define IDM_PREVIOUS5                   2017
#define IDM_PREVIOUSPAGE                2018
#define IDM_TOGGLEPS                    2019
#define IDM_ZOOMIN                      2020
#define IDM_ZOOMOUT                     2021
#define IDS_HELPMENU                    2022
#define IDS_MOVEMENU                    2023
#define IDS_VIEWMENU                    2024
#define IDM_FILE_RECENT                 2100
#define IDM_FILE_RECENT1                2101
#define IDM_FILE_RECENT2                2102
#define IDM_FILE_RECENT3                2103
#define IDM_FILE_RECENT4                2104
#define IDM_FILE_RECENT5                2105
#define IDM_FILE_RECENT6                2106
#define IDM_FILE_RECENT7                2107
#define IDM_FILE_RECENT8                2108
#define IDM_FILE_RECENT9                2109
#define ID_BUTTON40028                  40028
#define ID_BUTTON40029                  40029
#define ID_BUTTON40030                  40030
#define ID_BUTTON40031                  40031
#define ID_BUTTON40032                  40032
#define ID_BUTTON40033                  40033
#define ID_BUTTON40034                  40034
#define ID_BUTTON40035                  40035
#define ID_BUTTON40036                  40036
#define ID_BUTTON40037                  40037
#define ID_BUTTON40038                  40038
#define IDM_TOGGLEGRID                  40039
#define IDM_REDRAWPAGE                  40040
#define IDM_VIEW_LOG                    40043
#define ID_OPTIONS_TEXCONFIG            40046
#define ID_OPTIONS_WINDVI               40047
#define ID_BUTTON40048                  40048
#define IDM_NAVIGATEBACK                40048
#define IDM_URLBACK                     40049
#define IDM_BOOKMODE                    40050
#define IDM_SRCSPECIALS                 40051
#define IDS_SCSIZE                      61440
#define IDS_SCMOVE                      61456
#define IDS_SCMINIMIZE                  61472
#define IDS_SCMAXIMIZE                  61488
#define IDS_SCCLOSE                     61536
#define IDS_SCRESTORE                   61728
#define IDS_SCTASKLIST                  61744
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         40052
#define _APS_NEXT_CONTROL_VALUE         1033
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
