/* Header for module notes, generated by p2c 1.21alpha-07.Dec.93 */
#ifndef NOTES_H
#define NOTES_H


#ifndef CONTROL_H
#include "control.h"
#endif


#ifdef NOTES_G
# define vextern
#else
# define vextern extern
#endif


extern short count64['9' + 1 - '0'];


extern Void processNote PP((Char *note, Char *xnote, int dur1, Char *dur,
			    short *count));
extern Char durationCode PP((Char *note));
extern Char octaveCode PP((Char *note));
extern Void removeOctaveCode PP((int code, Char *note));
extern Void insertOctaveCode PP((int code, Char *note));
extern Void translateSolfa PP((Char *nt));


#undef vextern

#endif /*NOTES_H*/

/* End. */
