/EXPORT: TECkit_Compile=TECkit_Compile
/EXPORT: TECkit_CompileOpt=TECkit_CompileOpt
/EXPORT: TECkit_DisposeCompiled=TECkit_DisposeCompiled
/EXPORT: TECkit_GetCompilerVersion=TECkit_GetCompilerVersion
