.\" This manpage is licensed under the GNU Public License
.TH FIXMSXPART 1 2015-02-05  "" ""

.SH NAME
fixmsxpart \- corrects note spacing in a single-staff MusiXTeX part

.SH SYNOPSIS
.B fixmsxpart 
.RB  [ \-v\ |\ \-\-version\ |\ \-h\ |\ \-\-help ]

.B fixmsxpart
.RB [ \-d\  | \ \-\-debug ]
.IR infile [ \fB.tex\fB ]
.RI [ outfile [ \fB.tex\fP ]]


Converts a single-staff MusiXTeX part (possibly derived from a multi-instrument score and as a result having irregular note spacing) to a single-staff part with proper spacing determined by the notes themselves.

If 
.IR outfile 
is not specifed, standard output is used.

.SH USAGE

.SS Generating a Single-Instrument Part

To generate a single-instrument part from (a copy of) the MusiXTeX source for
a  multi-instrument score, add
.nf

    \\input musixtnt

.fi
to the preamble,
set 
.nf

    \\instrumentnumber1

.fi
and use the \\TransformNotes macro defined in musixtnt.tex to discard all but one part.
For example, the following line placed 
after
\\startpiece (but before any note commands) would be appropriate for
a
.IR four -instrument 
score (arguments #2, #3, #4, and #5, separated by three &s),  
and will result in a part for the 
.IR second 
of these (#3):

.nf
    \\TransformNotes{#2&#3&#4&#5}{#3}
.fi

Argument #1 is a scaling
parameter and should not be modified.
.B
It is essential that every \\znotes, \\notes, \\Notes, \\NOtes, etc. command in the score match the macro  pattern exactly; 
insufficient (or too many) note segments 
will result in lost text and possibly compilation failure; see
.BR msxlint (1).
It is assumed by \\TransformNotes that notes commands are terminated by \\en (rather than \\enotes).

Some additional manual changes to the source will be necessary:
.TP 3
+
adjustments of \\setname1, \\setclef1, \\setsign1 , \\setmeter1 and \\setstaffs1 commands, as necessary;
.TP 3
+
ensuring that tempo and roadmap markings 
.RB ( D.C. , 
.BR Fine , 
etc.) are in the
appropriate instrument segment;
.PP
Finally, if the modified score is compiled and viewed, it may be seen that horizontal
spacing designed for 
.I multiple 
instruments often produces bad
spacing for a 
.IR single 
instrument.
This can be corrected manually (and very tediously) but it is 
what
.B fixmsxpart
was designed to fix (much more conveniently).

.SS Correcting Horizontal Spacing Using fixmsxpart
The 
\\notes \\Notes \\NOtes \\NOTes...
commands in a
part derived from a multi-instrument score are unreliable,
and so 
.B fixmsxpart
determines the spacing for ordinary notes by the note
commands themselves; for example, 
.TP 3
+
\\qa, \\qu, \\ql, \\qp result in
\\NOtes; 
.TP 3
+
\\ca, \\cu, \\cl, \\ds result in \\Notes; 
.PP
and so on. 
Spacing commands \\sk and \\hsk in the input are 
discarded (but \\qsk, \\hqsk and explicit uses of \\off{...} are preserved). 
 
.B fixmsxpart
determines the spacing for 
.IR beamed 
notes by the beam
multiplicity: \\ib... results in \\Notes, \\ibb... results in
\\notes, etc. Some beam-termination commands (\\tb...) are
problematic because the immediately-following beam note
\\qb... must be spaced according to the spacing 
.IR before
the \\tb... command. This is handled by setting a
variable 
.IR new_beaming 
when processing the \\tb... command
and only updating 
.IR beaming 
to 
.IR new_beaming 
when processing 
the subsequent beam note.  This isn't needed for the 
abbreviations \\tqb, \\tqh, \\ztqb and \\ztqh which combine beam-termination and 
specification of the
final beam note.
 
.IR Pointed 
notes are 
.IR not 
given extra space 
automatically. They should be given extra space manually 
in the score 
by using either a \\roff-like command on the subsequent 
note or the \\qsk or \\hqsk spacing commands.

Additional features of
.BR fixmsxpart 
transformation:
.TP 3
+
Successive whole-bar rests are 
accumulated into a multi-bar rest, with appropriate adjustment of the bar number.
.TP 3
+
\\alaligne
and \\alapage commands are replaced by \\bar.
.TP 3
+
\\mulooseness, \\eject, \\linegoal, \\song{top | bottom}, \\group{top | bottom} 
and \\akkoladen
commands are commented out.
.TP 3
+
\\instrumentnumber...  commands become
\\instrumentnumber1. 
.TP 3
+
\\nostartrule is added to 
the preamble.
.TP 3
+ 
Simple slurs or ties initiated by \\slur or \\tie are normalized by
setting the 
.IR n 
parameter to 1 on the 
assumption that the new note spacing is correct.

.SH LIMITATIONS
Only single-staff instrumental parts are supported. User-defined macros are not expanded. 
A few esoteric MusiXTeX commands 
and constructions are not supported.

.SH SEE ALSO
.BR msxlint (1)
.PP 
musixdoc.pdf

.SH AUTHOR 
This program and manual page were written by Bob Tennent <rdt@cs.queensu.ca>.
