.TH FIXWPPS 1 "PSUtils Release @RELEASE@ Patchlevel @PATCHLEVEL@"
.SH NAME
fixwpps \- filter to fix WP documents so PSUtils work
.SH SYNOPSIS
.B fixwpps 
< 
.I WordPerfect.ps
>
.I Fixed.ps
.SH DESCRIPTION
.I Fixwpps
is a 
.I perl 
filter which "fixes" PostScript from WordPerfect 5.0 and 5.1 so
that it works correctly with Angus Duggan's
.B psutils
package.
.SH AUTHOR
Copyright (C) Angus J. C. Duggan 1991-1995
.SH "SEE ALSO"
@MAN@
.SH TRADEMARKS
.B PostScript
is a trademark of Adobe Systems Incorporated.
