.TH FIXWWPS 1 "PSUtils Release @RELEASE@ Patchlevel @PATCHLEVEL@"
.SH NAME
fixwwps \- filter to fix Windows Write documents so PSUtils work
.SH SYNOPSIS
.B fixwwps 
< 
.I WinWrite.ps
>
.I Fixed.ps
.SH DESCRIPTION
.I Fixwwps
is a 
.I perl 
filter which "fixes" PostScript from Windows Write so
that it works correctly with Angus Duggan's
.B psutils
package.
.SH AUTHOR
Copyright (C) Angus J. C. Duggan 1991-1995
.SH "SEE ALSO"
@MAN@
.SH TRADEMARKS
.B PostScript
is a trademark of Adobe Systems Incorporated.
