.TH INCLUDERES 1 "PSUtils Release @RELEASE@ Patchlevel @PATCHLEVEL@"
.SH NAME
includeres \- filter to include resources in a PostScript document
.SH SYNOPSIS
.B includeres 
< 
.I document.ps
>
.I output.ps
.SH DESCRIPTION
.I Includeres
includes resources (fonts, procsets, patterns, files, etc) in place of
.I %%IncludeResource
comments in a PostScript document. The resources are searched for in the
current directory and the system default directory under the resource name,
and with an appropriate extension.
The pipeline
.sp
.ce
extractres file.ps | includeres >out.ps
.sp
will move all resources appearing in a document to the document prologue,
removing redundant copies. The output file can then be put through page
re-arrangement filters such as
.I psnup
or 
.I pstops
safely.
.SH AUTHOR
Copyright (C) Angus J. C. Duggan 1991-1995
.SH "SEE ALSO"
@MAN@
.SH TRADEMARKS
.B PostScript
is a trademark of Adobe Systems Incorporated.
.SH BUGS
.I includeres
does not alter the
.I %%DocumentNeededResources
comments.
