.TH PDFTOOLS "1" "December 2006" "pdftools 1.2" "ConTeXt"
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.de EX
.in +3
.nf
.ft CW
..
.de EE
.in -3
.ft R
.fi
..

.SH NAME
pdftools \- analyze PDF files, change image colors
.PP
.SH "SYNOPSIS" 
\fBpdftools\fP [ \fIOPTION\fP ...  ] <file> [ <file> ... ]

.SH DESCRIPTION

\fBpdftools\fP analyzes PDF files and changes image colors.
It is used by the ConTeXt programs.  The image-processing features are
not documented here (since I don't understand what they do).
.PP 
.SH "OPTIONS" 
.PP 
.IP "\fB--help\fP" 
Print the available options.
.IP "\fB--analyzefile\fP" 
Print statistics about each PDF file, including
size, number of xforms, annotations, links, etc.
.IP "\fB--info\fP" 
Print, in XML format, information about the PDF files.
It gives the number of pages, producer, author, subject, creation date,
bounding boxes, ...  See also \fBpdfinfo\fP(1).
.IP "\fB--countpages\fP" 
Print the number of pages in each PDF file.

.SH "SEE ALSO" 
.PP
\fBtexexec\fP(1), \fBpdfinfo\fP(1), \fBpdftk\fP(1)
.PP
The pdftools manual \f(CWmpdftools.pdf\fP
available from
.URL "http://www.pragma-ade.com/dir/general/manuals/" "PRAGMA ADE" .
.PP
.URL "http://www.contextgarden.net" "ConTeXt wiki" .
.PP
.URL "http://www.adobe.com/devnet/pdf/pdf_reference.html" "The PDF specification" .

.SH "AUTHOR" 

This (incomplete) manual page was written by Sanjoy Mahajan
<sanjoy@mit.edu>.   It is in the public domain.
