.TH "PSTOPDF" "1" "December 2006" "pstopdf 2.0" "ConTeXt" 
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.de EX
.in +3
.nf
.ft CW
..
.de EE
.in -3
.ft R
.fi
..

.SH "NAME" 
pstopdf \- convert EPS to PDF

.SH "SYNOPSIS" 
\fBpstopdf\fP [ \fIOPTION\fP ...  ] \fIFILE\fP [ ...  ]

.SH "DESCRIPTION" 
 
\fBpstopdf\fP converts EPS (encapsulated PostScript) to PDF.

.SH OPTIONS
.TP
.B --help
Print usage and version information.
.TP
.B --convert
Convert EPS to PDF.  This option is assumed if none is given.
.TP
.BI --method=\fIstring\fP
What method to use for bounding boxes when converting to PDF.
Specify one of \fBcrop\fP, \fBbounded\fP (the default), or \fBraw\fP.
Older versions of ConTeXt used numerical methods (1, 2, or 3).
.TP 
.BI --resolution=\fIstring\fP
The resolution to use when when converting to pdf.
Specify one of \fBlow\fP, \fBnormal\fP, \fBmedium\fP, \fBhigh\fP,
\fBprinter\fP, \fBprint\fP, \fBscreen\fP, \fBebook\fP, or
\fBdefault\fP.
.TP
.B --request
Handle exa request file.
.TP
.B --watch
Watch folders for conversions (\fIuntested\fP).

.SH EXAMPLES

To make \fIcow.pdf\fP:
.EX
pstopdf cow.eps
.EE
or (one of several equivalents):
.EX
pstopdf --convert cow.eps cow.pdf
.EE


.SH "SEE ALSO" 
.PP
.BR epstopdf (1),
.BR mptopdf (1),
.BR ps2pdf (1),
.BR texexec (1).
.PP
.URL "http://www.contextgarden.net" "ConTeXt wiki" .

.SH "AUTHOR" 
This (incomplete) manual page was written by Sanjoy Mahajan
<sanjoy@mit.edu>.  It is in the public domain.
