.TH TEXFONT "1" "December 2006" "texfont 2.2" "ConTeXt"
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.de EX
.in +3
.nf
.ft CW
..
.de EE
.in -3
.ft R
.fi
..

.SH NAME
texfont \- font installation tool for ConTeXt

.SH "SYNOPSIS" 
\fBtexfont\fP [ \fIOPTION\fP ...  ]

.SH DESCRIPTION

TeXFont is a 
.BR perl (1)
script that helps to set up and install TeX fonts.
It was designed for use with ConTeXt, but may also be helpful for
users of other formats, like plain TeX or LaTeX. Its use is described
in detail in the files \fImtexfont.pdf\fP and \fImfont.pdf\fP.

.SH "OPTIONS" 

.HP
\fB\-\-fontroot\fR=\fIpath\fR : texmf font root (automatically determined)
.HP
\fB\-\-sourcepath\fR=\fIpath\fR : when installing, copy from this path (default: .)
.HP
\fB\-\-sourcepath\fR=\fIauto\fR : locate and use vendor/collection
.HP
\fB\-\-vendor\fR=\fIname\fR : vendor name (first level directory)
.HP
\fB\-\-collection\fR=\fIname\fR : font collection (second level
directory)
.HP
\fB\-\-encoding\fR=\fIname\fR : encoding vector (default: texnansi)
.HP
\fB\-\-slant\fR=\fIs\fR : slant glyphs in font by factor (0.0 - 1.5)
.HP
\fB\-\-extend\fR=\fIs\fR : extend glyphs in font by factor (0.0 - 1.5)
.HP
\fB\-\-caps\fR=\fIs\fR : capitalize lowercase chars by factor (0.5 - 1.0)
.HP
\fB\-\-noligs\fR : remove ligatures
.HP
\fB\-\-install\fR : copy files from source to font tree
.HP
\fB\-\-listing\fR : list files on auto sourcepath
.HP
\fB\-\-remove\fR : remove files on auto sourcepath
.HP
\fB\-\-makepath\fR : when needed, create the paths
.HP
\fB\-\-test\fR : use test paths for vendor/collection
.HP
\fB\-\-show\fR : run tex on texfont.tex
.HP
\fB\-\-batch\fR : process given batch file
.HP
\fB\-\-weight\fR : multiple master weight
.HP
\fB\-\-width\fR : multiple master width
.HP
\fB\-\-expert\fR : also handle expert fonts
.HP
\fB\-\-help\fR : show some more info
.HP
.SH "SEE ALSO" 
.PP
\fBtexexec\fP(1), \fBfontinst\fP(1), \fBperl\fP(1), \fBtexshow\fP(1).
.PP
The ConTeXt Font manual, \fImfonts.pdf\fP
available from
.URL "http://www.pragma-ade.com/dir/general/manuals/" "PRAGMA ADE" .
.PP
The TeXFont manual, \fImtexfont.pdf\fP
.PP
The TeXExec manual, \fImtexexec.pdf\fP.
.PP
.URL "http://www.contextgarden.net" "ConTeXt wiki" .
.PP
Donald E. Knuth\'s \fIThe TeXbook\fP.

.SH "AUTHOR" 

This manual page was written by Frank K\[:u]ster <frank@kuesterei.ch>,
for the Debian GNU/Linux system, and  modified by Sanjoy Mahajan
<sanjoy@mit.edu>.  It may be used and modified by others without
contacting the authors.
