.TH "TEXUTIL" "1" "December 2006" "texutil 9.1" "ConTeXt"

.SH "NAME" 
texutil \- ConTeXt utility program

.SH "SYNOPSIS" 
\fBtexutil\fP [ \fIOPTION\fP... ] \fIFILENAME\fP[...]

.SH "DESCRIPTION" 

This program, whether as a Perl or the newer ruby script, is
deprecated and many of its features are available in
\fBctxtools\fP(1), \fBgs\fP(1), \fBpdftools\fP(1), and
\fBtexexec\fP(1).

.SH SEE ALSO

\fBctxtools\fP(1), \fBgs\fP(1), \fBpdftools\fP(1), \fBtexexec\fP(1)

.SH "AUTHOR" 

This incomplete man page was written by Sanjoy Mahajan
<sanjoy@mit.edu> and is in the public domain.
