#!/bin/sh
# $Id: calendar3-stdout,v 1.1 2003/08/15 19:40:37 tom Exp $
: ${DIALOG=dialog}

USERDATE=`$DIALOG --extra-button --extra-label "Hold" --help-button --stdout --title "CALENDAR" --calendar "Please choose a date..." 0 0 7 7 1981`

case $? in
  0)
    echo "Date entered: $USERDATE.";;
  1)
    echo "Cancel pressed.";;
  2)
    echo "Help pressed.";;
  3)
    echo "Hold pressed.";;
  255)
    echo "Box closed.";;
esac
