#!/bin/sh
# $Id: calendar3,v 1.4 2003/10/09 22:45:06 tom Exp $
: ${DIALOG=dialog}

exec 3>&1
USERDATE=`$DIALOG --extra-button --extra-label "Hold" --help-button --title "CALENDAR" --calendar "Please choose a date..." 0 0 7 7 1981 2>&1 1>&3`
code=$?
exec 3>&-

case $code in
  0)
    echo "Date entered: $USERDATE.";;
  1)
    echo "Cancel pressed.";;
  2)
    echo "Help pressed.";;
  3)
    echo "Hold pressed.";;
  255)
    echo "Box closed.";;
esac
