#!/bin/sh
# $Id: gauge3,v 1.3 2008/07/22 23:48:56 tom Exp $
: ${DIALOG=dialog}

(
sleep 1
for n in 0 1 2 3 4 5 4 3 2 1 0
do
PCT=`expr $n \* $n \* 4`
cat <<EOF
XXX
$PCT
The new\n\
message ($PCT percent)
XXX
EOF
sleep 1
done
) |

$DIALOG --title "GAUGE" --gauge "Hi, this is a gauge widget" 10 70 0
