#!/bin/sh
# $Id: timebox2-stdout,v 1.1 2003/08/15 19:40:37 tom Exp $
: ${DIALOG=dialog}

USERTIME=`$DIALOG --stdout --title "TIMEBOX" --timebox "Please set the time..." 0 0`

case $? in
  0)
    echo "Time entered: $USERTIME.";;
  1)
    echo "Cancel pressed.";;
  255)
    echo "Box closed.";;
esac
