/* Made by newbuild.pl; DO NOT EDIT !!!   -*- C -*- */
#ifndef VERSION__9C077E32_49F9_4a99_9A1F_3E4C4DB17C7D__INCLUDED_H_
#define VERSION__9C077E32_49F9_4a99_9A1F_3E4C4DB17C7D__INCLUDED_H_
#define TEXLIVE_PRODUCTNAME_STR "TeXLive"
#define TEXLIVE_COMPANYNAME_STR "TeX Users Group"
#define TEXLIVE_BUILD_COMMENT_STR "Build 25 (2003); build date: Tue Aug 19 14:51:44 2003; machine: ANSIBLE"
#define TEXLIVE_BUILD_DATE 1061297504
#define TEXLIVE_BUILDERNAME_STR "popineau"
#define TEXLIVE_PRIVATEBUILD_STR "Built by popineau"
#define TEXLIVE_MAJOR_VERSION 8
#define TEXLIVE_MINOR_VERSION 0
#define TEXLIVE_BETA_NUMBER 1
#define TEXLIVE_BETA_NUMBER_STR "1"
#define TEXLIVE_ALPHA_NUMBER 0
#define TEXLIVE_ALPHA_NUMBER_STR "0"
#define TEXLIVE_PATCH_NUMBER 0
#define TEXLIVE_PATCH_NUMBER_STR ""
#define TEXLIVE_BUILD_LABEL "2003"
#define TEXLIVE_BUILD_NUMBER 25
#define TEXLIVE_BUILD_SPECIAL_STR ""
#define TEXLIVE_MAJOR_VERSION_STR "8"
#define TEXLIVE_MINOR_VERSION_STR "0"
#define TEXLIVE_BETA_VERSION_STR "1"
#define TEXLIVE_ALPHA_VERSION_STR "0"
#define TEXLIVE_BUILD_NUMBER_STR "25"
#define TEXLIVE_RELEASE_STATE 0
#define TEXLIVE_RELEASE_MOTTO_STR ""
#define TEXLIVE_PRODUCTVERSION_STR "8"
#define TEXLIVE_LIBRARYPREFIX_STR "tl80"
#ifndef TEXLIVE_LEGALCOPYRIGHT_STR
#define TEXLIVE_LEGALCOPYRIGHT_STR "Copyright (C) 1996-2003 Fabrice Popineau and the TeX Users Group"
#endif
#ifndef TEXLIVE_LEGALTRADEMARKS_STR
#define TEXLIVE_LEGALTRADEMARKS_STR ""
#endif
#endif
