/* config.h:
 * In the original package this file is generated by autoheader.
 * When part of the teTeX / TeX live tree, we simply include
 * c-auto.h as generted by autoheader and configure. */

#ifndef _CONFIG_H
#define _CONFIG_H

#include "c-auto.h"

#endif /* _CONFIG_H */
